### ISSUE TITLE
xiaomi 4i ROM 5.7.3 miuisystem.apk can decompile, but back to compile error

### ISSUE THREAD

**Issue by basten1899** [iBotPeaches/Apktool#1000]
D:\APKTOOL>apktool d miuisystem.apk
I: Using Apktool 2.0.1 on miuisystem.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\xxxxxxxxxx\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\xxxxxxxxxx\apktool\framework\16.apk
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\APKTOOL>apktool b miuisystem
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
D:\APKTOOL\miuisystem\res\layout\app_list_item.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/app_icon').

D:\APKTOOL\miuisystem\res\layout\app_list_item.xml:5: error: Error: No resource found that matches the given name (at 'id' with value '@id/app_name').

D:\APKTOOL\miuisystem\res\layout\app_picker.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/list').

D:\APKTOOL\miuisystem\res\layout\cloud_panel.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '@drawable/cloud_panel_bg_light').

**Comment by laststandingdroid** [comment]
Seems like you have some missing id's and drawables

in ids.xml app_name isn't defined same goes with ids.xml list isn't defined.

cloud_panel_bg_light isn't either found.

Seems like it isn't decompiled successfully after all

**Comment by laststandingdroid** [comment]
C:\Users\SSPD-ABODE1\Downloads\00-MOD START\NEW MOD BLUE\2.12.161122\res\values\public.xml:1747: 
error: Public symbol drawable/st1f3c3 declared here is not defined.                                                                            C:\Users\SSPD-ABODE1\Downloads\00-MOD START\NEW MOD BLUE\2.12.161122\res\values\public.xml:1748:
error: Public symbol drawable/st1f3c4 declared here is not defined.                                                                            

This is probably caused by missing files or not being used

**Comment by iBotPeaches** [comment]
Same root caused as #1049
