### ISSUE TITLE
Change aapt to have a target SDK option ?

### ISSUE THREAD

**Issue by phhusson** [iBotPeaches/Apktool#1017]
One problem I've came across multiple times, is that on rebuild, aapt decides some attributes are for the latest sdk (ie API 22 for current AAPT release), while the APKs might be for older versions of Android, but with added attributes, so the attributes 
This is done in aapt's ResourceTable::getPublicAttributeSdkLevel function.
Having an option in apktool b which is forwarded to aapt to specify API version would help fix/workaround those problems.
Another way would be to detect API version from framework-res, and apply this max API

**Comment by phhusson** [comment]
(I first noticed this on MTK 5.0 devices)

**Comment by furzewolf** [comment]
I had the same problem modifying a Samsung TouchWiz 4.4.2 ROM. Building with the default API 22 resulted in UI bugs including checkboxes not being visible in the compiled app. I had to download the API 19.1 AAPT to the Apktool directory and use the flag --aapt aapt.exe to resolve the problem (thanks to @phhusson).

**Comment by iBotPeaches** [comment]
aapt has the following parameters.

```
   --min-sdk-version
       inserts android:minSdkVersion in to manifest.  If the version is 7 or
       higher, the default encoding for resources will be in UTF-8.
   --target-sdk-version
       inserts android:targetSdkVersion in to manifest.
   --max-res-version
       ignores versioned resource directories above the given value.
```

Apktool sets all of these (assuming the `AndroidManifest.xml` provides target/min/max sdk values). 

The function `getPublicAttributeSdkLevel` in `aapt` is just checking at which AOSP API did that resource become public, or -1 if not public, etc. I'm not sure of the side effects of overriding this with an api option.

The easy solution is if you require a less restrictive aapt, then use `--aapt /path/to/aapt` which whatever version of aapt you require. 

This is proving to be a problem though, so I will have to dig around aapt some more and see if there is any potential tweaks available.

**Comment by iBotPeaches** [comment]
Maybe it would help if I had a location of all previous aapts for (win, mac and unix)? As you may or may not know, using the stock aapts are a bit difficult in some edge case scenarios (which is where our apktool modified aapt come into play).

However, every new aapt released removes the previous patched one from existence. I can go through git history and pull the old ones into a directory structure of like

`aapt / API version / [mac/unix/win]`

and upload that somewhere for everyone to benefit from.

**Comment by phhusson** [comment]
If you already have a custom version of aapt (I thought you were using stock one, I haven't found the source of apktool's aapt), I'd suggest adding a new option to aapt for that.
Having different aapts is a possibility, though it would require to be properly documented, especially since the effects are non-trivial (you need to hit a bug before thinking about using another aapt).

From what I've seen, getPublicAttributeSdkLevel returning 22 makes the matching layout (drawable, ...) being in two samples. one in res/layout/ without this attribute, and one in res/layout-v22/ with all the attributes.

I haven't actually checked it's this function which creates this behaviour, but it's the only one I'm seeing in aapt's source which might explain this behaviour.

**Comment by phhusson** [comment]
In ResourceTable.cpp, there is a rather long comment before status_t ResourceTable::modifyForCompat(const Bundle* bundle):
explaining the problem, and how they solve it:

 * We get around this by detecting any newly defined attributes (in L),                                                     
 * copy the resource into a -v21 qualified resource, and delete the                                                         
 * attribute from the original resource. This ensures that older platforms                                                  
 * don't see the new attribute, but when running on L+ platforms, the                                                       
 * attribute will be respected.

(more details in the file: https://github.com/iBotPeaches/platform_frameworks_base/blob/apktool/tools/aapt/ResourceTable.cpp#L4412 )

I guess no-oping this function might be enough

**Comment by iBotPeaches** [comment]
Since apktool handles already built apks (obviously), apktool shouldn't modified them intentionally (like aapt is doing).

We need aapt though to do the build, so thanks to the initial research from @phhusson I'm skipping any method/check that modifies any files. This should drastically reduce the amount of apks broken by the newer aapt. My testing with the linux binary is proving to be good. I will build the mac/windows binaries and release the aapts for some testing before I merge them into mainline .

**Comment by Sandrichka22** [comment]
I've used both Apktool version 2.1.0 and 2.2.0 to decode an apk, replace some drawables (.png files in resources) and build the .apk again. I now have a problem with the drawables, more precisely, i use them as icons for notifications and they are now both white, something that happens when you raise the sdk level to 19 or above. This is exactly the reason why the sdk level of my application is 17. Can the aapt version may be the reason for this or am I just writing on a wrong thread. Sorry if this is the case. What would be the solution if the problem is the aapt?

**Comment by iBotPeaches** [comment]
@Sandrichka22 The SDK level of aapt in apktool rises with every AOSP release. You simply can't use an older aapt with newer builds of Android and aapt attempts to keep backwards compatibility.

If the newer aapt is changing the brightness of your images, then this could either be

1. A bug in the 9patch decoder in apktool.
2. A bug/feature in the newer aapt release.
3. Expected functionality due to image optimizations provided by new aapt.

The parameter `--aapt` exists for this reason. You can go find old aapts (SDK version to match your preference) and pass the full absolute path to this file to apktool as a parameter. Apktool will use that aapt for builds (taking away any custom apktool parameters), but using that aapt inside of its internal one.

Fixes for the 9patch went in at 2.1.0, so both 2.1.0 and 2.2.0 would have had this problem and the aapt internally hasn't changed since 2.0.2. You might need to open a new bug with a ton of details, providing a test case, expected image (before/after) as these issues are difficult to track down without all the details provided.

**Comment by Sandrichka22** [comment]
Good to know that you can use an older aapt and pass it to apktool as parameter. In the end I ended up designing new icons that look good even if they are completely whitened on the status bar on some devices (everything that has color in the icon is turned white, and the transparent parts remain transparent). Just to be on the record in case someone else needs this information, the issue happened to me when running the .apk on HTC M8 running Android 6.0. I did not try to use an old version of aapt as I needed a solution fast and replacing the icon with another one was the most easy thing to do at the moment.

**Comment by bjethwan** [comment]
How come I am still facing this, I thought you removed the --max-res-version check???

C:\>apktool b luavmandroid
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: max res 23, skipping values-v24
W: max res 23, skipping values-v25
W: C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res\values\public.xml:1026: error: Public symbol style/Platform.V25.AppCompat declared here is not defined.
W: C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res\values\public.xml:1027: error: Public symbol style/Platform.V25.AppCompat.Light declared here is not defined.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KH1783\AppData\Local\Temp\brut_util_Jar_3220204063785814529.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --max-sdk-version, 23, --max-res-version, 23, --version-code, 1, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\KH1783\AppData\Local\Temp\APKTOOL8947390463230457646.tmp, -0, arsc, -0, arsc, -I, C:\Users\KH1783\AppData\Local\apktool\framework\1.apk, -S, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res, -M, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)

**Comment by bjethwan** [comment]
Is there a command line param I can tweak to disable that option so you don't send it over to aapt?

**Comment by iBotPeaches** [comment]
@bjethwan This has nothing to do with this ticket. Please don't mix up threads with unrelated reports.

**Comment by iBotPeaches** [comment]
For aapt1
```
        if (mMaxSdkVersion != null) {
            cmd.add("--max-sdk-version");
            cmd.add(mMaxSdkVersion);

            // if we have max sdk version, set --max-res-version
            // so we can ignore anything over that during build.
            cmd.add("--max-res-version");
            cmd.add(mMaxSdkVersion);
        }
```

I believe aapt2 does this automatically now. Also, no response in 3+ years so I believe this is resolved anywho.
