### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by SSOOnline** [iBotPeaches/Apktool#1035]
ApkTool has many incompatible problems, such as the jar package contains the resources can not support,.So file containing the APK compatibility is not good, but packed special tags in the AndroidManifest.xml file will be lost

**Comment by iBotPeaches** [comment]
> ApkTool has many incompatible problems, such as the jar package contains the resources can not support

What does this mean? Contains resources that it can't support? Every internal framework inside of apktool is supported by itself, thats how I test to make sure apktool is ready for that API version.

> So file containing the APK compatibility is not good, but packed special tags in the AndroidManifest.xml file will be lost

What is `special tags`? You mean attributes on xml tags? If so that is already bug.


Either way, I'm closing this. There is nothing productive or helpful in this report.
