### ISSUE TITLE
resource id changed when build apk using the default aapt.exe in apktool

### ISSUE THREAD

**Issue by mrFranklin** [iBotPeaches/Apktool#1089]
when I use my aapt.exe(" -a aapt.exe"), there is no error.but when I using the default aapt.exe in apktool, some resource id changed !

I was always using the defalut aapt.exe in apktool before, but one day I got the runtime errors:
"java.lang.IllegalArgumentException: No view found for id 0x7070025 (com.xxx.xxx:dimen/com_facebook_likeboxcountview_text_padding) for fragment LoginFragment"

My step is:
1. apktool decode apk
2. add some resources into the output directory
3. generate R file
4. backsamli R.java
5. apktool buid apk

I fount the resource id equals 0x7070025 in smali file is "com_facebook_fragment_container";
(R$id.smali: .field public static final com_facebook_fragment_container:I = 0x7f070025)
but after "apktool build" it changes to “dimen:com_facebook_likeboxcountview_text_padding"  which equals 0x7080025 before. (I decode the apk again, and check it in public.xml).  and the resource :"com_facebook_fragment_container" changed to 0x7090025 !

after using the option "-a mypath/aapt.exe", everything is OK!

**Comment by iBotPeaches** [comment]
When you say using "my appt". What does that mean? Is this a custom aapt? A specific Android platform version aapt?

The current version of Apktool has internally the API 23 aapt.

**Comment by mrFranklin** [comment]
Yes, it is a custom aapt.exe. the version is 19.1.0
when I replaced my aapt.exe to API 23.0.2, it occurs the error below:
ERROR: Asset package include 'C:\Users\***\apktool\framework\1.apk' not found.
     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
     at brut.androlib.Androlib.buildResources(Androlib.java:403)
     at brut.androlib.Androlib.build(Androlib.java:291)
     at brut.androlib.Androlib.build(Androlib.java:261)
     at brut.apktool.Main.cmdBuild(Main.java:225)
     at brut.apktool.Main.main(Main.java:84)

but when I used the aapt inside apktool， there is no compiling error. (but occuring the error what I explained before)

**Comment by iBotPeaches** [comment]
Yes, that error is because the updated `aapt` requires each package to have an `AndroidManifest.xml` file. A constraint that is viable for devices, but unintentionally constrained the host side of the tools.

This is why we have a custom aapt of the most up to date aapt binary, in which these bugs/changes are fixed. 

Your use case / method is making me nervous. We avoid requiring to rebuild the `R.java` file by leveraging `public.xml` to keep the resource ids constant. Since you are rebuilding the `R.java` (and thus changing the resource ids), any modern Android build system would correctly update the resource id references.

I built a simple test applications with one resource, decoded, rebuilt, decoded the rebuilt application and the resource id never changes. I haven't tried this with Facebook yet (seems to be what you are decoding), but maybe something is amiss with how you are using apktool & aapt or I don't fully understand yet.

**Comment by iBotPeaches** [comment]
Resource IDs aren't changing for me with the included aapt and binary. Closing this due to some non-standard method.
