### ISSUE TITLE
Publish to Jcenter/MavenCenral or make Jitpack ready

### ISSUE THREAD

**Issue by jaredsburrows** [iBotPeaches/Apktool#1142]
It would be nice to push this to Jcenter and/or MavenCentral but definitely have this repository Jitpack ready.

**Comment by iBotPeaches** [comment]
I'm not aware of JitPack ready and I assume JCenter is another Maven like repository for storing binaries. I feel the tool needs my limited time and effort towards actually fixing bugs, and with 0 knowledge of ever publishing anything to either of these, it might take some time to research and learn what I need to do to support this.

**Comment by jitpack-io** [comment]
Hi @iBotPeaches 
JitPack builds and publishes GitHub repositories automatically so you won't have to do anything additional. Looks like someone already used version 2.0.3: https://jitpack.io/#iBotPeaches/Apktool

**Comment by jaredsburrows** [comment]
@jitpack-io @iBotPeaches Yes. I have tried using this jitpack with this repo and it didn't seem to work well.

**Comment by iBotPeaches** [comment]
I just examined the link posted above. It didn't have the proper build commands. It didn't even complete compilation, so not sure why it said "get it". Those versions @jaredsburrows will not work.

I'd have to find a way to override however jitpack is building, because standard gradle configuration is not how we build this tool.

**Comment by jitpack-io** [comment]
Ah, ok, there are custom build steps http://ibotpeaches.github.io/Apktool/build/.
By default JitPack runs the `install` task so perhaps these steps can be run before install.

**Comment by omervk** [comment]
Please note that @jitpack-io is experiencing build errors when trying to build 2.0.3 (2.0.2 builds fine).

See: https://jitpack.io/com/github/iBotPeaches/Apktool/2.0.3/build.log

**Comment by iBotPeaches** [comment]
2.0.2 isn't valid either. None of the binaries it has ever generated are correct. This is now feeding incorrect binaries into the world.

I signed into the application and removed all binaries. There is no feature (I read the documentation) to override the build steps. It "looks" like 2.0.2 built, because it had a 0 exit code. However, the build did not complete because the correct parameters were not passed.

Apktool in its `2.0.3` state requires two commands from a clean install (recursive clone), as the build guide recommends. This service is not running those, thus erroring out.

If and when this service ever gets a custom build option, then we can revisit. Even then, it probably won't work, because our compilation takes some extra tools that aren't part of the standard Gradle build set. You may reference our `.travis.yml` file to see those changes - https://github.com/iBotPeaches/Apktool/blob/master/.travis.yml

You can get proper binaries here - https://bitbucket.org/iBotPeaches/apktool/downloads

**Comment by omervk** [comment]
Thank you.

**Comment by Lanchon** [comment]
FYI, there an unofficial repo here:
https://dexpatcher.github.io/dexpatcher-repo/
