### ISSUE TITLE
Recompiling APK results in parsing error

### ISSUE THREAD

**Issue by sreekanths22** [iBotPeaches/Apktool#1208]
### Information
1. **Apktool Version (`apktool -version`)** - 2.,0.3
2. **Operating System (Mac, Linux, Windows)** - Windows 7 
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. I have build an app using PhoneGap Build. It had some issues with the permissions (App asked for all permissions, despite setting the parameter to none) and I read that it is better to decompile using Apktool, edit AndroidManifest.xml and recompile it.
2. I did all that. Now, when I try to install it, I get the "There was a problem parsing the package." error.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? No.
3. Are you using the latest apktool version? Yes.

Please advise.

Sreekanth

**Comment by iBotPeaches** [comment]
Hm. Thanks for following this new issue template, but there is a few missing things. Initially since you said you got "There was a problem parsing the package" which means the app installed failed but the real details hide among `adb logcat`.

Please run `adb logcat` during the install of the application and obtain the real stacktrace. Or provide the apk, there is simply not enough information here to do anything on.

**Comment by iBotPeaches** [comment]
Closing due to no response in a few months.

**Comment by ikhwanreza** [comment]
i got same problem, please help,

OS --> Mac
