### ISSUE TITLE
versionName reference instead of literal value fails

### ISSUE THREAD

**Issue by padlar** [iBotPeaches/Apktool#1234]
2.1.0/Mac/https://www.dropbox.com/s/0c6kwrqoutxtfh5/sampleapp.apk?dl=0

### Steps to Reproduce
Run the app as it is to see the versionName.
Now, decode, build and run the app without making any changes. On running, you will see that the versionName is null. versionName is read using the following piece of code -

			PackageManager packageManager = getApplicationContext().getPackageManager();
			PackageInfo packInfo = packageManager.getPackageInfo(getApplicationContext().getPackageName(),0);
			text2.setText("VersionName = " + packInfo.versionName);

**Comment by iBotPeaches** [comment]
There is no `versionCode` in this application and `versionName` is a reference instead of a literal value.

Prior to the world of Gradle, you could use a reference, but with Gradle it will choke if you try and use a reference in the gradle configuration. This is such a small priority edge case. Please manually extract the literal value from the reference and use it as this is not on my radar for a fix any time soon.

The alternative is having Apktool detect a string reference in `versionName` and extract the literal value from that reference and then using that literal value in the parameter passed to `aapt`. In the past I've written functions that track down literal values from references, but these modified the original apk inserting said literal value which I don't like any more as that changes the original.

If anyone would like to submit a pull request. Please don't modify the original files, so just grab the value of the reference and pass that to `AndroidLibResources`. Accepting PRs to fix this.

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/commit/3e566930c75f69c0655f68afac481236fae53a0e

Fixed. Thanks!
