### ISSUE TITLE
Feature Request: CLI switch to merge multi-dex files into one classes.dex

### ISSUE THREAD

**Issue by socraticbliss** [iBotPeaches/Apktool#1252]
It now seems to be fairly commonplace to split dex files in APK's

Naturally, this can be used to deter people trying to de-compile an APK, as many users will not know that they need to smali->jar the other folders if they want to view all of the classes

I've found that with a multi-dex APK, I can manually copy the smali'ed files into the main smali folder and have it merge everything together into one classes.dex on rebuild

It would be really nice to have a command line switch option in order to have this done automatically when de-compiling/re-compiling in case there was multiple dex files, I looked into the Androlib.java and see where it could be done, however I think it would be a valuable addition to Apktool in general!

**Comment by iBotPeaches** [comment]
Some applications split for organization, but most split apks are because the dex method limit has been reached and they have no other option. If we hit the method limit then a single `dex` file is useless. This means Apktool shouldn't try and merge multi-dex apks together.

Apktool is not meant to repair or modify apk's in this regard. Its goal and is to provide a nearly 1 to 1 match from decoded to original.

**Comment by socraticbliss** [comment]
Okay, thanks for the clarification, I'll modify it on my end for my use case :+1:  :)
