### ISSUE TITLE
input directory ''APKTOOL4052771454481 984918.tmp' does not exist

### ISSUE THREAD

**Issue by leol1912** [iBotPeaches/Apktool#1293]
Info 
Apktool Version 2.1.1
OS Win7
Apk selfmade

Hello,

My problem is that im able to decompile my app but im not abe to recompile it.
Tried it several times, always the same error.

I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: input directory 'C:\Users\User\AppData\Local\Temp\APKTOOL4052771454481
984918.tmp' does not exist

can somebody please help me?

**Comment by iBotPeaches** [comment]
Apktool writes temporary files in order to build the final apk. It seems the file can't be written and/or is being deleted before apktool can read it.

This value is from the `java.io.tmpdir` environment variable. You can update this to another value by prefixing this command after java like so `java -Djava.io.tmpdir=C:\Users\Location\To\New\Area`

**Comment by leol1912** [comment]
Thank You!
This could fix it.
