### ISSUE TITLE
Folder smali_classes2

### ISSUE THREAD

**Issue by mega7star** [iBotPeaches/Apktool#1294]
### Information
1. **Apktool Version (`apktool -version`)** - 2.0.2
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Google Play

Hi, i have this project structure:
![screen](https://cloud.githubusercontent.com/assets/1462355/17230680/561c2f00-5526-11e6-83dc-910b76e7a78f.PNG)
What is folder `smali_classes2`? This folder has the same files as in a folder `smali` (*.smali). 
How it looks in the source code in Android Studio project?
This is very similar to the `#pragma data_seg` on C++.

**Comment by iBotPeaches** [comment]
`smali` = `classes.dex`
`smali_classes2` = `classes2.dex`

This is used in MultiDex apps - https://developer.android.com/studio/build/multidex.html

**Comment by mega7star** [comment]
Thanks, @iBotPeaches! 
What classes (methods) are inserted into `classes2.dex`? (Developers can specify which?)
And can be an application, which is less than 64K methods and contains 2 or more dex?

**Comment by iBotPeaches** [comment]
I'm not sure what decides which method goes where. I've never been on the development side of making one of these applications. 

You probably can have as many dex files as you want if you leverage the DexLoader on your own.

**Comment by mega7star** [comment]
Ok, thanks!

**Comment by dlabsch** [comment]
Hi,
i ran into a problem and need help...or an explanation.
After decoding whatsapp, i got this mysterious smali_classes2 folder too.
When I try to build the .apk again i got a lot of errors. With every other app I'm able to decode and rebuild without any problems. Is there a way to rebuild whatsapp again?
The Errors:
C:\Users\dominicl\4_11\1318>java -jar C:\Users\dominicl\Desktop\apktool_2.2.1.jar b base
I: Using Apktool 2.2.1
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\dominicl\4_11\1318\base\res\values-television-v13\mipmaps.xml:3: error: Resource entry launcher_icon is already defined.
W: res\mipmap-television-v13\launcher_icon.xml:0: Originally defined here.
W:
W: C:\Users\dominicl\4_11\1318\base\res\values\strings.xml:929: error: Error parsing XML: not well-formed (invalid token)
W:
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6030: error: Public symbol string/account_item_default declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6087: error: Public symbol string/action_card_folder_color declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6161: error: Public symbol string/app_descr declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6172: error: Public symbol string/app_name declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6179: error: Public symbol string/appbar_scrolling_view_behavior declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6186: error: Public symbol string/auth_google_play_services_client_facebook_display_name declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6187: error: Public symbol string/auth_google_play_services_client_google_display_name declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6247: error: Public symbol string/cell_palette_decimal_places_value_format declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6258: error: Public symbol string/character_counter_pattern declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6474: error: Public symbol string/com.google.android.apps.docs.quickoffice.HomeActivity declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6475: error: Public symbol string/com.qo.android.quickpoint.Quickpoint declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6476: error: Public symbol string/com.qo.android.quickword.Quickword declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6734: error: Public symbol string/document_info_panel_time_last_modified declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6740: error: Public symbol string/document_metrics_document_count declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6741: error: Public symbol string/document_metrics_loading declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6763: error: Public symbol string/document_type_google_site_v2 declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6906: error: Public symbol string/exporting_document declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6938: error: Public symbol string/file_picker_my_device_heading declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:6996: error: Public symbol string/ga_trackingId declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7003: error: Public symbol string/google_app_name declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7146: error: Public symbol string/logo_title declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7148: error: Public symbol string/m_font_family_title declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7244: error: Public symbol string/menu_show_team_drives declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7447: error: Public symbol string/opened_document declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7461: error: Public symbol string/ouch_authorize_database_dump declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7574: error: Public symbol string/palette_paragraph_linespacing_format declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7575: error: Public symbol string/palette_paragraph_linespacing_format_sketchy declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7615: error: Public symbol string/pasteDisabled declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7624: error: Public symbol string/permsearch declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7625: error: Public symbol string/permsearch_desc declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7681: error: Public symbol string/prefs_about_category_key declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7687: error: Public symbol string/prefs_category_content_description declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7722: error: Public symbol string/primes_marker declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7783: error: Public symbol string/recent_activity_users_one declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7799: error: Public symbol string/remove_file_message declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7800: error: Public symbol string/remove_file_title declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7843: error: Public symbol string/rlz_access_points declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:7857: error: Public symbol string/save_failed_dialog_title declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8152: error: Public symbol string/table_palette_column_width_format declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8169: error: Public symbol string/table_palette_row_height_format declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8224: error: Public symbol string/template_category_a11y_text declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8225: error: Public symbol string/template_category_education declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8226: error: Public symbol string/template_category_letters declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8227: error: Public symbol string/template_category_personal declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8228: error: Public symbol string/template_category_resumes declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8229: error: Public symbol string/template_category_work declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8233: error: Public symbol string/template_list_brand_link declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8234: error: Public symbol string/template_list_brand_no_link declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8235: error: Public symbol string/template_list_item_a11y_text declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8236: error: Public symbol string/template_list_item_a11y_text_branded declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8237: error: Public symbol string/template_style_apa declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8238: error: Public symbol string/template_style_beach_day declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8239: error: Public symbol string/template_style_blue_and_gold declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8240: error: Public symbol string/template_style_bold_dark declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8241: error: Public symbol string/template_style_bold_light declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8242: error: Public symbol string/template_style_bright declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8243: error: Public symbol string/template_style_coral declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8244: error: Public symbol string/template_style_gameday declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8245: error: Public symbol string/template_style_geometric declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8246: error: Public symbol string/template_style_grape_juice declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8247: error: Public symbol string/template_style_lively declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8248: error: Public symbol string/template_style_luxe declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8249: error: Public symbol string/template_style_marina declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8250: error: Public symbol string/template_style_material declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8251: error: Public symbol string/template_style_mla declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8252: error: Public symbol string/template_style_modern_writer declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8253: error: Public symbol string/template_style_paperback declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8254: error: Public symbol string/template_style_playful declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8255: error: Public symbol string/template_style_plum declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8256: error: Public symbol string/template_style_pop declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8257: error: Public symbol string/template_style_serif declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8258: error: Public symbol string/template_style_simple declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8259: error: Public symbol string/template_style_simple_dark declared here is not defined.
Exception in thread "main" W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8260: error: Public symbol string/template_style_simple_light declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8261: error: Public symbol string/template_style_slate declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8262: error: Public symbol string/template_style_spearmint declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8263: error: Public symbol string/template_style_swiss declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8264: error: Public symbol string/template_style_tropic declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8265: error: Public symbol string/template_style_western declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8266: error: Public symbol string/textSelectionCABTitle declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8292: error: Public symbol string/toast_not_a_neo_build declared here is not defined.
W: C:\Users\dominicl\4_11\1318\base\res\values\public.xml:8336: error: Public symbol string/unrepresentable_value_format declared here is not defined.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dominicl\AppData\Local\Temp\brut_util_Jar_1941691347977450799.tmp
, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 60920840, --version-name, 1.6.092.08.40, -F, C:\Users\dominicl\AppData\Local\Temp\APKTOOL332601393460444
5433.tmp, -0, arsc, -0, assets/t, -0, arsc, -I, C:\Users\dominicl\AppData\Local\apktool\framework\1.apk, -S, C:\Users\dominicl\4_11\1318\base\res, -M, C:\Users\dominicl\4_11\1318\base\AndroidManifest.
xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        at brut.androlib.Androlib.buildResources(Androlib.java:412)
        at brut.androlib.Androlib.build(Androlib.java:311)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dominicl\AppData\Local\Temp\brut_util_Jar_1941691347977450799.tmp, p, --forced-package-
id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 60920840, --version-name, 1.6.092.08.40, -F, C:\Users\dominicl\AppData\Local\Temp\APKTOOL3326013934604445433.tmp, -0, arsc, -0
, assets/t, -0, arsc, -I, C:\Users\dominicl\AppData\Local\apktool\framework\1.apk, -S, C:\Users\dominicl\4_11\1318\base\res, -M, C:\Users\dominicl\4_11\1318\base\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\dominicl\AppData\Local\Temp\brut_util_Jar_1941691347977450799.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, -
-target-sdk-version, 23, --version-code, 60920840, --version-name, 1.6.092.08.40, -F, C:\Users\dominicl\AppData\Local\Temp\APKTOOL3326013934604445433.tmp, -0, arsc, -0, assets/t, -0, arsc, -I, C:\User
s\dominicl\AppData\Local\apktool\framework\1.apk, -S, C:\Users\dominicl\4_11\1318\base\res, -M, C:\Users\dominicl\4_11\1318\base\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more

C:\Users\dominicl\4_11\1318>

**Comment by shikhaverma2009** [comment]
Hi, 
I try to add a new smali file in smali folder but its not working. But if i modify already created smali file it is working. My question is can I add a new smali file in decompiled apk? 
Please help !
