### ISSUE TITLE
Apktools doesn't decomplie dex files in the assets folder

### ISSUE THREAD

**Issue by GoyfAscetic** [iBotPeaches/Apktool#1312]
If an app has dex files in the assets directory apktools does not decompile them.
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows with Cygwin
3. **APK From? (Playstore, ROM, Other)** - Playstore
### Stacktrace/Logcat

N/A
### Steps to Reproduce
1. `apktool`  d <apk directory> -f -o <output directory>
2. Check the assets directory they're be a dex directory with a number of untouched dexfiles
### Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
### APK

https://drive.google.com/file/d/0B0FOvv6OHq5aUHk2enhlNFBqZHM/view?usp=sharing
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Not Modified
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
This is intentional behavior currently. I stupidly didn't reference the bug when I made commit, but there were applications with dex files in the non-root directory thus apktool would unpack them and then pack them into the root of application breaking the original purpose.

https://github.com/iBotPeaches/Apktool/commit/76a940628f7a34aeed02ea228d42fc5a6d1d7356

Apktool has no folder structure for dex files yet. It simply unpacks and packs them back to root of apk. This would be a feature enhancement to support dex files in unknown areas.

**Comment by iBotPeaches** [comment]
I believe this was fixed now. We find multiple sources and even with `--main-classes-only` flag to undo the greedy behavior.
