### ISSUE TITLE
Staged aapt execution for large amount of compressed files.

### ISSUE THREAD

**Issue by JustDragon** [iBotPeaches/Apktool#1335]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/heroes-charge/com.ucool.hero

I just decompile the apk, then recompile and the rebuild apk is so much bigger. From 30 MB jump to 65 MB, and I have this bug in some others apk also.

**Comment by iBotPeaches** [comment]
Can't be fixed currently. This APK has one extension (`.ddx`) that is sometimes deflated and sometimes stored. 

Apktool previously wrote the absolute path to each file needed to be deflated, however that caused a problem due to applications much like this one that has a ton of files. This makes the generated command  far too long to execute, thus fails.

AAPT has update support so theoretically we could go back to absolute paths per compressed file and execute after we've hit ~50 files to keep the command low. However, our aapt code for executing the binary is currently expecting it to be ran once instead of x times.

Would be a large rewrite of the internal code that communicates with aapt. Marking this as a feature enhancement for the back burner.

**Comment by JustDragon** [comment]
Thank you very much for answering me. In the meantime, the easy fix is drag assets,lib out and drag them back in with 7zip

**Comment by iBotPeaches** [comment]
Cleaning up tracker. Merging this into #1272

Same goal, one bug. A staged aapt execution for unknown files.
