### ISSUE TITLE
Problem decompilation res

### ISSUE THREAD

**Issue by aleks921** [iBotPeaches/Apktool#1358]
I use apktool 2.2.1 and try decompilation resource http://rgho.st/92bGKrQyT
But all files of resourse have name 2_APKTOOL_DUPLICATENAME_0x7f04000a.
Screen of bag: http://data3.floomby.com/files/share/3_11_2016/11/BKoPJ4J70O3RHzEKwNQLQ.jpg

**Comment by iBotPeaches** [comment]
What do you expect apktool to do in this instant? All resource names are the same due to obfuscation. Android only cares about the IDs, so the names can be anything. Apktool in order to decode needs unique names per configuration so it creates these duplicate name tags intentionally in order to allow decode. It basically is `APKTOOL_DUPLICATENAME_[RES_ID]`.

The real names of these resources cannot be retrieved. This is intentional.

**Comment by aleks921** [comment]
How this apk build after change ?
I try compile with apktool 2.2.1 but get error about resource.
How fixed this error ?
[log_recompile.txt](https://github.com/iBotPeaches/Apktool/files/569714/log_recompile.txt)

**Comment by tianzhijiexian** [comment]
has you fix it? @aleks921
