### ISSUE TITLE
I found that doNotCompress does not work in apktool.yml?

### ISSUE THREAD

**Issue by lpcdma** [iBotPeaches/Apktool#1373]
### Assets directory part of the file is not compressed, I think it is configured doNotCompress,but did not take effect.
1. test 2.2.0 2.2.1.
2. win10 64bit.

**Comment by iBotPeaches** [comment]
The template for issue reports is here for a reason. I can't take action if you remove every bullet point and/or question I have. There are a couple outstanding reports regarding `doNotCompress`, but due to lack of details in this ticket. I am closing this.

Feel free to open another, but please follow the template.
