### ISSUE TITLE
Apktool adds api version itself on resource folders.

### ISSUE THREAD

**Issue by acsway878787** [iBotPeaches/Apktool#1458]
### Information
1. **Apktool Version (`apktool -2.2.2`)** 
2. **Operating System (`Windows`)** 
3. **APK From? (`ROM`)** 
4. **ROM Info(`ASUS Padfone S 4.4..2 stock`)**

### Steps to Reproduce
1. `apktool if framework-res.apk`
`apktool d SystemUI.apk`
`apktool b SystemUI.apk `

### Frameworks
[https://www.dropbox.com/s/q91od465qiy0jt2/framework-res.apk?dl=0](https://www.dropbox.com/s/q91od465qiy0jt2/framework-res.apk?dl=0)

### APK
[https://www.dropbox.com/s/nmha0buv1w22rjh/SystemUI.apk?dl=0](https://www.dropbox.com/s/nmha0buv1w22rjh/SystemUI.apk?dl=0)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? `Yes`
2. If you are trying to install a modified apk, did you resign it? `Not doing this.`
3. Are you using the latest apktool version?  `Yes.`

### Problematic screenshots
[https://imgur.com/a/ZE2Pf](https://imgur.com/a/ZE2Pf)

**Comment by iBotPeaches** [comment]
Hmmm. How did this happen. I built both the Windows & Unix binaries from the same codebase, yet I confirm this on Windows.

https://github.com/iBotPeaches/platform_frameworks_base/commit/99d5bf68d18bfb64a439a670a38bceb079fef97b

I guess I need to rebuild Windows binaries. I wish TravisCI could be adapted to test Windows as well.

**Comment by iBotPeaches** [comment]
Bumping this into the upcoming release. This is a problem at the apktool level & aapt.

**Comment by iBotPeaches** [comment]
After a weekend of research, there is not much I can do here, well maybe but here is the deal. Apktool currently iterates through resources after it processes the `resources.arsc` file. Some of these are resources contained within said file, while others are files located elsewhere in the apk

So imagine a file resource in the configuration `drawable-xhdpi`, it may have no version qualifier there, but in my testing the reference in the `resources.arsc` file has `sdkVersion` set to `4`. This is because AAPT does some crazy smart detective work where it uses the `minSdkVersion` from `AndroidManifest.xml` in order to detect in any resource used from higher Android releases. This implicitly adds the resource at the `ResResource` value. This is why you don't see versions in the folder qualifications but they decode with them.

So I did a test. I make a brand new application with the current Android Studio with SDK Tools, assuming thats what most developers do (ie using the latest stuff).

My directories were `drawable-[mdpi/hdpi/xhdpi/xxhdpi/xxxhdpi]`, then they were all implicitly added with versions as shown below.

```
➜  apk aapt d configurations app-debug.apk 
mdpi-v4
hdpi-v4
xhdpi-v4
xxhdpi-v4
xxxhdpi-v4
➜  apk 
```

```
➜  apk zipinfo -l app-debug.apk 
Archive:  app-debug.apk
Zip file size: 73956 bytes, number of entries: 16
-rw-rw-rw-  2.3 unx     1972 b-      750 defN 80-000-00 00:00 AndroidManifest.xml
-rw----     2.4 fat     1211 b-     1062 defN 80-000-00 00:00 META-INF/CERT.RSA
-rw----     2.4 fat     1511 b-      737 defN 80-000-00 00:00 META-INF/CERT.SF
-rw----     2.4 fat     1449 b-      695 defN 80-000-00 00:00 META-INF/MANIFEST.MF
-rw----     2.4 fat     2760 b-     1359 defN 80-000-00 00:00 classes.dex
-rw-rw-rw-  2.3 unx     3122 b-     3122 stor 80-000-00 00:00 res/mipmap-hdpi-v4/ic_launcher.png
-rw-rw-rw-  2.3 unx     4208 b-     4208 stor 80-000-00 00:00 res/mipmap-hdpi-v4/ic_launcher_round.png
-rw-rw-rw-  2.3 unx     1956 b-     1956 stor 80-000-00 00:00 res/mipmap-mdpi-v4/ic_launcher.png
-rw-rw-rw-  2.3 unx     2555 b-     2555 stor 80-000-00 00:00 res/mipmap-mdpi-v4/ic_launcher_round.png
-rw-rw-rw-  2.3 unx     4366 b-     4366 stor 80-000-00 00:00 res/mipmap-xhdpi-v4/ic_launcher.png
-rw-rw-rw-  2.3 unx     6114 b-     6114 stor 80-000-00 00:00 res/mipmap-xhdpi-v4/ic_launcher_round.png
-rw-rw-rw-  2.3 unx     7007 b-     7007 stor 80-000-00 00:00 res/mipmap-xxhdpi-v4/ic_launcher.png
-rw-rw-rw-  2.3 unx    10056 b-    10056 stor 80-000-00 00:00 res/mipmap-xxhdpi-v4/ic_launcher_round.png
-rw-rw-rw-  2.3 unx     9490 b-     9490 stor 80-000-00 00:00 res/mipmap-xxxhdpi-v4/ic_launcher.png
-rw-rw-rw-  2.3 unx    14696 b-    14696 stor 80-000-00 00:00 res/mipmap-xxxhdpi-v4/ic_launcher_round.png
-rw-rw-rw-  2.3 unx     2064 b-     2064 stor 80-000-00 00:00 resources.arsc
16 files, 74537 bytes uncompressed, 70237 bytes compressed:  5.8%
➜  apk 
```

And the original

```
/home/ibotpeaches/Projects/Java/Issue1458/app/src/main/res
➜  res ls
drawable     mipmap-mdpi   mipmap-xxhdpi   values
mipmap-hdpi  mipmap-xhdpi  mipmap-xxxhdpi
➜  res 
```

So I believe are only chance at resolving this would be.

Cross reference directory full path name vs resource qualifier, so `drawable-hdpi` stays as such even though resource has `sdkVersion=4`. This would mean that it would leverage the directory name instead of what the qualifiers say. This is probably a mess to program with all the rules, you would think we already do that, but we don't - aapt does that during compilation.

So pending we do that change, our builds of aapt don't add implicit qualifiers so that build of the application won't have any set, their `sdkVersion` will be 0. This could potentially be bad if AOSP requires in a certain circumstance to have the version qualifier that we have now wiped them, because remember the previous change would trust the directory file path instead of qualifier. 

This would be a breaking change to existing applications. The original reason we stopped implicit versioning during build was to match applications to original nearly 100%. The problem now is decoding implicit versioning.

TDLR - Doing no change. This is too dangerous to change currently.

**Comment by iBotPeaches** [comment]
As per my last reply. I looked into this again and without dangerously breaking things. There is nothing more I can do at the non-folder qualifier level.
