### ISSUE TITLE
Error message after trying to use the tool in this manner:   apktool -d app.apk and got the following error:   Files\Android\android-studio\jre\jre\bin"" was unexpected at this time.  

### ISSUE THREAD

**Issue by jetav8r** [iBotPeaches/Apktool#1488]
### Information
1. **Apktool Version (`apktool -version`)** - latest version  2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - other

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool -d app.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Sounds like you are having a java problem. Doesn't look like a bug, looks like an environment problem.

**Comment by jetav8r** [comment]
Why do you guys close issues before any suggestions to resolve them???
java is fine.... If I run java - version at the command prompt, it shows
version 1.8 so that's not it... thanks for dismissing this so quickly...not
helpful at all

On Thu, Apr 27, 2017 at 11:36 AM, Connor Tumbleson <notifications@github.com

**Comment by jetav8r** [comment]
Why do you guys close issues before any suggestions to resolve them???
java is fine.... If I run java - version at the command prompt, it shows version 1.8 so that's not it... thanks for dismissing this so quickly...not helpful at all

**Comment by iBotPeaches** [comment]
Okay, lets see here.

1) This is a free, open source hobby ran project. I do not have the time to do 1 on 1 support. If there was a Java problem running Apktool. I can 100% be sure that one of the hundreds of people who use apktool daily would have reported it.

2) I ask for a simple template. This is so I can sit down without wasting time asking the submitter the same questions every time. You didn't do anything to my template besides the first 3 questions. You simply made a title and submitted the bug report. So imagine my surprise when I get a notification and email for a bug report with no contents! I have to sit here deciphering a bug report from only the title and operating system and version. 

3) Using this knowledge I have, this can be summed down to "Windows - Apktool 2.2.2 doesn't work with "_other_" application". Actually it does. I test on Ubuntu (unix) and Windows (Windows 10 64bit) for nearly every commit to prevent regression. I know this because I pushed a commit a few days ago when I explicitly tested the build and use on Windows, so I know from personal experience it does work. Additionally, hundreds of users use Apktool on Windows on XDA and it works for them as well.

4) This is a bug tracker. Not a support forum. This is not a bug. This is you skipping installation instructions and/or struggling on a step. Let me remind you again, install docs are here - https://ibotpeaches.github.io/Apktool/install/

They are basic and easy to follow. Do those again.

**Comment by jetav8r** [comment]
Ridiculous...I followed your steps exactly as you said... Like I said..NOT
at java issue.  The only "template" information I can provide was this:
I installed it exactly as your steps provided. I get that it's open source
and it's a "hobby" for you.  I'm an Android developer with more experience
than the number of years you have been alive, so please don't patronize me
by saying "They are basic and easy to follow. Do those again."  I'm not an
idiot or a child, and asked for some simple guidance.  If you don't have
time or the answer, you could have simply left the item open for someone
else to help with.  I'm simply trying to use your tool to easily open the
apk.  I will just use a different tool and go through the steps required to
decompile individually.  Your tool is an excellent idea and I'm sure it is
helpful to many people.

On Thu, Apr 27, 2017 at 12:00 PM, Connor Tumbleson <notifications@github.com

**Comment by yongyanghz** [comment]
Hi, When I put the `apktool.bar` and `apktool.jar` in `C:\Windows`，first time I executed ` apktool`, it worked and showed the help manual,  and second time and after I executed ` apktool`,  it showed ' Files was unexpected at this time.`
So then I added path to System variables , it works fine. It is  probably a path issue.

**Comment by dsx12** [comment]
I found the issue for me was my environment variable "PATH" had an extra ";" attached to it. Check your PATH variable and see if the issue persists.

**Comment by FeedMyLlama** [comment]
It was definitely your java

**Comment by kzu** [comment]
Funniest thing, after finding #2078 , is that if instead of using the .bat you just do `java -jar apktool_2.4.1.jar d xxx.apk` instead, it Just Works. So, something's screwed up in the .bat. (to reiterate: I get a similar error with the .bat, no error with java -jar explicitly).
