### ISSUE TITLE
what meaning of  WARNING: linker: Warning: unable to normalize ""


### ISSUE THREAD

**Issue by longcheng973428** [iBotPeaches/Apktool#1491]
i use the apk ，and it show the world:WARNING: linker: Warning: unable to normalize ""
what meaning？

**Comment by iBotPeaches** [comment]
Do you have a full stacktrace? That is a basic unix error, I need to see it in context.

**Comment by longcheng973428** [comment]
i am use application，and it's show :WARNING: linker: Warning: unable to normalize ""

**Comment by iBotPeaches** [comment]
Not enough information to go on. In the future, please keep the issue template in tact to make things easier. I'm still unable to gather info details to figure out this problem.

**Comment by deepu2** [comment]
He may have been talking about the apktool x for android, I stumbled upon here since I've got this error myself.

Anyway when importing framework, this is the error -
>  WARNING: linker: Warning: unable to normalize ""
> I: Framework installed to: /data/data/per.pqy.apktool/1.apk


When decompiling SystemUI.apk the error is -

>  WARNING: linker: Warning: unable to normalize ""
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
> 	at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:157)
> 	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
> 	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
> 	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:106)
> 	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
> 	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:94)
> 	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:46)
> 	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:96)
> 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:127)
> 	at brut.apktool.Main.cmdDecode(Main.java:165)
> 	at brut.apktool.Main.main(Main.java:81)
I: Using Apktool 2.0.3-Black on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /data/data/per.pqy.apktool/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...

It does decompile the apk. But when I try to recompile this, it gives an error and doesn't recompile
 
> WARNING: linker: Warning: unable to normalize ""
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
> 	at brut.androlib.Androlib.readMetaFile(Androlib.java:263)
> 	at brut.androlib.Androlib.build(Androlib.java:275)
> 	at brut.androlib.Androlib.build(Androlib.java:268)
> 	at brut.apktool.Main.cmdBuild(Main.java:225)
> 	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
> 	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:105)
> 	at brut.androlib.Androlib.readMetaFile(Androlib.java:258)
> 	... 4 more
I: Using Apktool 2.0.3-Black

I'm sorry if this is not the place for these issues and for formatting issues if any 🤐

**Comment by jjanzer** [comment]
LD_LIBRARY_PATH probably has an empty path eg: export LD_LIBRARY_PATH=/data/some/custom/: instead of LD_LIBRARY_PATH=/data/some/custom
