### ISSUE TITLE
Huawei apks

### ISSUE THREAD

**Issue by Persona78** [iBotPeaches/Apktool#1521]
![capturar](https://cloud.githubusercontent.com/assets/17556394/26643013/bf8ee548-4627-11e7-8b47-9fd46b8e8f64.PNG)

Hi!
Huawei apks have errors and we can´t decompile it.
It is possibel to insert a decompile/compile ignore option?
Like this we can tweak it and then compile it.

Thanks.

.

**Comment by iBotPeaches** [comment]
Huawei isn't supported due to qualifier changes. Sorry. This however, does not look like a qualifier problem, but I need applications and logs in text.

A screenshot of a log simply isn't enough for me to do anything. If you can attach an apk we can revisit this.

**Comment by Persona78** [comment]
Hi!
This is the Huawei apk that i was trying to decompile.
https://mega.nz/#!9xBU3Z4D!RDi8esxQGA19V26h4szKF-GISWT1mhBYOKicczcEh54

People say that Huawei insert error to avoid decompiling ( i don´t know if is true... )

Thanks

**Comment by iBotPeaches** [comment]
Downloaded. Will check and update ticket. Might need framework files - not sure yet.

**Comment by Persona78** [comment]
Hi!
This is framework:
https://mega.nz/#!41ozxAAL!bqtfZUKAhcdduu07NzTbJNtg6KDlgREfvKOfM-j_peY

**Comment by iBotPeaches** [comment]
This apk has 3 `DEFAULT` configurations. Usually this is fine because those `DEFAULTS` are spread among various types or packages.

In this situation in Type 1, we have two `DEFAULT` configurations which causes duplicate resources. I tweaked apktool to log the qualifier name and then the remaining bytes (Usually the 4 bytes from 52 -> 56 in ResConfigHeader)

```
➜  Bug1521 apktool debug if framework-res-hwext.apk -t 1521
Listening for transport dt_socket at address: 5005
Remaining: 0x0
0-[DEFAULT]
Remaining: 0x0
1-[DEFAULT]
Remaining: 0x9C00
1-[DEFAULT]
W: Duplicate Resource Detected. Ignoring duplicate: string/wifi_switch_to_pdp_title
```

So whats happening is we are decoding type 0, `default` configuration then type 1 `default` configuration, then another type 1 `default` configuration. When in fact we can see from the output that is an additional 2 bytes `0x9C` of data. This is unknown. We don't know how to translate this to qualifiers, thus errors out.

This is not AOSP, we don't have source to examine and discover the meaning of this extra data. Not to mention this extra 4 bytes purpose was never discovered - https://github.com/iBotPeaches/Apktool/commit/67d80a133fd96bbf992db359725d8909e585f628

Perhaps its not Huawei specific, but only Huawei apks are failing with this error. So maybe they re-used this unknown 4 bytes of data for their own purpose.

**Comment by Persona78** [comment]
So, there is no way to decompile Huawei apks? There are few that works fine...

Hmmmm...

.

**Comment by iBotPeaches** [comment]
Correct. No support for Huawei as of now.

**Comment by kolboch** [comment]
Not sure if it is related but on Huawei mediapad t3 I was successful with decompiling the apk, however, after making minor changes in smali I was unnable to launch the recompiled app (resigned etc.). Even after  decompiling without touching resource files still got an Resources$NotFoundException error.

**Comment by iBotPeaches** [comment]
This is part of roadmap for plugin system since Huawei is reusing qualifiers for something else.

(Maybe not 3+ years later)

but have to clean up tracker - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#qualifier-plugin-system

Closing.
