### ISSUE TITLE
APK size before decoding and after re-encoding

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1572]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2 (edit: 2.2.4 also).
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64
3. **APK From? (Playstore, ROM, Other)** - Play store / apkmirror. Facebook (non-beta) from 7/25/17, Android 4.0.3.

### Steps to Reproduce
1. apktool d -s facebook.apk -o whatever
2. apktool b whatever -o facebook-repacked.apk
3. Compare sizes of facebook.apk and facebook-repacked.apk 

It seems like when rebuilding an APK file, apktool generates a file that's ~20MB larger than the source APK. I suspect compression settings are the main culprit here, since manually repacking the APK with full ZIP compression (zip -9) results in a substantially smaller file (even compared to stock).

This isn't directly causing any kind of malfunction per se, but it raises suspicion of introduction of rogue code (by end users of published modded APKs), as well as increases storage requirements.

**Comment by bovirus** [comment]
Please before to post issues check latest apktool version and use it.
You version is outdated.
The latest was 2.2.3 and from yesterday 2.2.4.

**Comment by evilwombat** [comment]
Thank you. The same behavior is observed on 2.2.4. Repacked APK is approximately 22MB larger than source.

**Comment by iBotPeaches** [comment]
Just to make my life easier, it seems to be this build - http://www.apkmirror.com/apk/facebook-2/facebook/facebook-134-0-0-25-91-release/facebook-134-0-0-25-91-4-android-apk-download/

I'll look into it soon.

**Comment by evilwombat** [comment]
Indeed. You want the ARM version. This is what I used:
http://www.apkmirror.com/apk/facebook-2/facebook/facebook-134-0-0-25-91-release/facebook-134-0-0-25-91-android-apk-download/download/

Thanks!

**Comment by iBotPeaches** [comment]
There are json files in `/assets` that are both STORED and DEFLATED. Apktool first encounters a `STORED` json file and thus records that extension as `STORED`.

This causes all `jsons` to be STORED. There is no support for this feature enhancement yet. Similar extensions that are stored differently is not something we have support for currently. This cannot be fixed until #1272 is solved, as this would amplify and make matters worse for that platform as this fix would require storing the relative file path to all individuals files in order to remember STORED vs DEFLATED at the file level instead of extension level.

I don't have a "blocked on" tag, so I'll just tag as bug for now.

**Comment by iBotPeaches** [comment]
All of the stored/compressed code was overhauled many times. This ticket is 4+ years old and many many releases have changed this. Going to close.
