### ISSUE TITLE
Use of external aapt for building apk

### ISSUE THREAD

**Issue by bingqiao** [iBotPeaches/Apktool#1774]
I have apktool embedded in a Spring Boot executable jar so that some extra processing is done before apktool is called to rebuild an apk.

Sometimes apktool fails to use the internal aapt (still investigating) and falls back to using the external one (by setting "aapt" in the command array instead of absolute path to the temp file generated from the internal aapt). The external aapt however doesn't work. I tried various aapt binaries from different versions of built-tools but none worked.

I went through this thread #1520 and believe I'm getting the same error "First type is not attr!".

I understand the internal aapt is patched and would like some clarification on whether non-patched aapt is no longer supported? Or if this is a temporary fix. But either way, it could be helpful to mention this in the documentation regarding the use of --aapt option.

Many thanks

**Comment by iBotPeaches** [comment]
Non-patched app is supported, but you are working with an application built in aapt2 and attempting to build with aapt1 (external). That is the reason you are getting that "first type is not attr" issue. There is nothing apktool can do there with a non-patched aapt1 binary in the context of a decoded aapt2 application.

There is 1 solution. Take the patched aapt for your system and add it to the system PATH, so that executing "aapt" runs the prebuilt patched binary. That should resolve your issue.

I'll leave this open until I read the docs about that parameter and check if it needs some additional information.

**Comment by iBotPeaches** [comment]
Updated docs: https://github.com/iBotPeaches/Apktool/commit/36e7f74e13359b253f9ab9c88643eadaafc1c54f

**Comment by bingqiao** [comment]
Thanks for the explanation. The docs for --use-aapt2 seems wrong.

Does apktool choose the right version of aapt when rebuilding the apk (it doesn't look so in the source code and I see calls to aapt1Package in verbose mode)? Does this option need (have) to be used for both decoding and rebuilding of an apk that was built using aapt2?

In addition, "aapt2 version" gives a text slightly different prior to android sdk 26.0.2.
"Android Asset Packaging Tool (aapt) 2.16"
There is no colon in that text so the following check fails:
`if (version.startsWith("Android Asset Packaging Tool (aapt) 2:")) {
            return 2;
        } else if (version.startsWith("Android Asset Packaging Tool, v0.")) {
            return 1;
 }`

**Comment by ibuprophen1** [comment]
@iBotPeaches, I hope that the following is helpful for what you are looking for. 

https://stackoverflow.com/questions/42082352/how-to-use-aapt2-where-is-the-documentation

https://stackoverflow.com/questions/46988102/errorcom-android-tools-aapt2-aapt2exception-aapt2-error-check-logs-for-detail


~Ibuprophen

**Comment by iBotPeaches** [comment]
Okay patched with version detection - https://github.com/iBotPeaches/Apktool/commit/3a33bfc48f22800ce7083d618deac9502fb7c068
