### ISSUE TITLE
Not able to decompile Chrome Beta v72

### ISSUE THREAD

**Issue by TyrionTheImp0417** [iBotPeaches/Apktool#1981]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Play Store/APK Mirror

### Steps to Reproduce
1. apktool d chrome.apk
2. All reources will have 0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_ and some id after that.

### APK
https://www.apkmirror.com/apk/google-inc/chrome-beta/chrome-beta-72-0-3626-53-release/chrome-beta-72-0-3626-53-2-android-apk-download/download/

**Comment by iBotPeaches** [comment]
This is intended and working. How is Apktool suppose to name resources if the application has all the resources named the same?

```
        resource 0x7f16001a com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000461 (s=0x0008 r=0x00)
        resource 0x7f16001b com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000462 (s=0x0008 r=0x00)
        resource 0x7f16001c com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000463 (s=0x0008 r=0x00)
```

Every resource is the same name, so in order to decode to human readable formats we need to make up a name.

**Comment by TyrionTheImp0417** [comment]
So are they using some other way to build apk's as all the resources are named like this. And will we be able to decode them? As Facebook is using something like this too.

**Comment by iBotPeaches** [comment]
> So are they using some other way to build apk's as all the resources are named like this. And will we be able to decode them?

Building apks might be difficult, but decoding should work. Those patches for `duplicateresourcename` was the exact patch to allow decoding of these applications.

**Comment by TyrionTheImp0417** [comment]
So if i understand correctly the file name will remain like this only even after this patch. The patch just make us to see what insides a file right?

**Comment by TyrionTheImp0417** [comment]
As the color value looks like this too
`<color name="0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f060007">@android:color/black</color>
    <color name="0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f06000d">#ff7fa87f</color>
    <color name="0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f06000e">@android:color/black</color>
    <color name="0_resource_name_obfuscated_APKTOOL_DUPLICATENAME_0x7f06000f">@android:color/black</color>`

**Comment by iBotPeaches** [comment]
Let me take a step back and explain a bit more.

You are looking at `colors.xml`, which if you peek inside an application with some zip viewer you won't find. This is because resources are packed into the `resources.arsc` file with two parts. 

Key and Value.

The key may be `link_color_text` with value of `@android:color/black`. However, you are looking at the human readable values of both those. When in fact the only required aspect of those is the key associated with both.

Lets take this example.

```
android:minSdkVersion(0x0101020c)=(type 0x10)0x12
```

It lists the human-readable key of `0x0101020c`, likewise `0x12` is the API key for whatever platform version that corresponds too.

What I'm getting at here, is this private application no longer has human readable keys. It has the same key for every resource, as shown here

```
 resource 0x7f16001a com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000461 (s=0x0008 r=0x00)
        resource 0x7f16001b com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000462 (s=0x0008 r=0x00)
        resource 0x7f16001c com.chrome.beta:xml/0_resource_name_obfuscated: t=0x03 d=0x00000463 (s=0x0008 r=0x00)
```

So when apktool decodes it, we have duplicate resource warnings everywhere. So Apktool, in order to decode the application makes up resource names. There are no original resource names in this application to even discover. They don't exist, they were stripped off at build time.

**Comment by TyrionTheImp0417** [comment]
Thanks for such a detailed explanation. And sorry for taking so much of your time. The explanation really helped me understand what's going on. 

Actually I am a themer so that's why was so concerned about this. Firstly it happened in Facebook now it has some folders like 
color2

Now this is coming to Google apps. Maybe they are using some obfuscating code that is causing this. Anyways it is what it is. 

Thanks again for such explanation and for making apktool.
