### ISSUE TITLE
decompile/recompile without changes fail

### ISSUE THREAD

**Issue by baptistapedro** [iBotPeaches/Apktool#2206]
I tried to recompile just after I decompiled, without doing any changes at all. I added the verbose(-v) mode however it does not show any stacktrace or something about the exception.
The apk im trying to recompile is Telegram - https://www.apkmirror.com/apk/telegram-fz-llc/telegram/telegram-5-10-0-release/ - open the link, fetch the first variant.

Just decompile it and try recompile again please and I believe it'll fail as well without any apparent reason. :/

**Comment by Ticklefish** [comment]
This is what I get if I decompile and try to recompile one of the latest APK's from that link:

" **31-10-2019@1032 --- Decompiling "test.apk" in "_WorkArea1", using "apktool_2.3.4.jar" with advanced settings: 

Forced Decode Of "AndroidManifest.xml" - ACTIVE 

Installed Framework File(s)

AOSP_10_framework-res.apk [1.apk]

(java -Xmx1024m -jar user_files\APKTOOL\apktool_2.3.4.jar d --force-manifest     -f -p _WorkArea1\Frameworks _WorkArea1\_in\test.apk -o _WorkArea1\_working\test.apk) 

I: Using Apktool 2.3.4 on test.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: _WorkArea1\Frameworks\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

31-10-2019@1032 --- File Decompiled 

------------

31-10-2019@1032 --- Recompiling "test.apk" in "_WorkArea1", using "apktool_2.3.4.jar" with advanced settings: 

Copying original "AndroidManifest.xml" and "META-INF" folder - ACTIVE 
Reassembling "resources.arsc" And "classes*.dex" files - ACTIVE 
Using "aapt2" [apktool_2.3.2+] - ACTIVE 

Installed Framework File(s)

AOSP_10_framework-res.apk [1.apk]

(java -jar user_files\APKTOOL\apktool_2.3.4.jar b --copy-original  --force-all --use-aapt2 -p _WorkArea1\Frameworks _WorkArea1\_working\test.apk -o _WorkArea1\_out\test.apk) 

I: Using Apktool 2.3.4
I: Smaling smali folder into classes.dex...
I: Building resources...
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:3: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:4: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:5: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:6: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:7: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:8: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:9: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:10: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:11: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:12: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:13: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:14: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:15: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:16: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:17: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:18: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:19: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:20: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:21: error: <item> inner element must either be a resource reference or empty.
W: C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res\values\ids.xml:22: error: <item> inner element must either be a resource reference or empty.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\LCHESN~1\AppData\Local\Temp\brut_util_Jar_2659295893367168473.tmp, compile, --dir, C:\TickleMyAndroid\_WorkArea1\_working\test.apk\res, --legacy, -o, C:\TickleMyAndroid\_WorkArea1\_working\test.apk\build\resources.zip]

31-10-2019@1033 --- File Not Recompiled** "

You can ignore a lot of the extra text - I use a program that uses apktool for my decompiling and recompiling. 
The important thing is the error message I got. This said that, for a lot of lines in a XML file, "**<item> inner element must either be a resource reference or empty**"
Put that into Google and the very first link tells you what the problem is and how to resolve it: [https://stackoverflow.com/questions/52076491/android-inner-element-must-either-be-a-resource-reference-or-empty](url)
Essentially you need to take every line that looks like this: "**<item type="id" name="acc_action_msg_options">false</item>**". They then need to look like this: "**<item type="id" name="acc_action_msg_options"/>**". 

Your APK should now compile.

**Comment by baptistapedro** [comment]
I have a different error
check this https://dpaste.de/bEQO/raw

**Comment by iBotPeaches** [comment]
```
➜  2206 apktool d org.telegram.messenger_5.10.0-16841_minAPI16\(armeabi-v7a\)\(nodpi\)_apkmirror.com.apk
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on org.telegram.messenger_5.10.0-16841_minAPI16(armeabi-v7a)(nodpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2206 apktool b org.telegram.messenger_5.10.0-16841_minAPI16\(armeabi-v7a\)\(nodpi\)_apkmirror.com --use-aapt2
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2206 
```

Can't replicate on latest.
