### ISSUE TITLE
When there is a directory named assets under the assets directory, error will occur when compiling

### ISSUE THREAD

**Issue by Nightreven** [iBotPeaches/Apktool#2406]
### Information
1. **Apktool Version (`apktool -2.4.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `  d E:\app-release-unsigned.apk  -o E:\app-release-unsigned
2. `apktool `   b E:\app-release-unsigned -o E:\test.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
http://www.mediafire.com/file/ad1r7m4wnuc7ukv/app-release-unsigned.apk/file

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?YES
2. If you are trying to install a modified apk, did you resign it?NO
3. Are you using the latest apktool version?YES

**Comment by giacomoferretti** [comment]
Couldn't reproduce with `2.4.2-d3f9d5-SNAPSHOT` on Linux.

**Comment by iBotPeaches** [comment]
As mentioned above. I could not reproduce as well.

```
➜  2406 apktool d app-release-unsigned.apk 
I: Using Apktool 2.4.2-987220-SNAPSHOT on app-release-unsigned.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2406 apktool b app-release-unsigned
I: Using Apktool 2.4.2-987220-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  2406 
```

**Comment by wenqiangtxc** [comment]
I reproduce  using latest version on Windows. 
When there is a directory named Assets(initial letter must be capitalized) in the assets directory, Other files in the assets directory will error.

I found out that it's because folder names are not case-sensitive in Windows. 
[When apktool iterating through the process assets folder](https://github.com/iBotPeaches/Apktool/blob/6d4e503b161d4225bd746a2f218f0130c0de86a3/brut.j.dir/src/main/java/brut/directory/ZipUtils.java#L57),`BrutIO.sanitizeUnknownFile()` return a file directory that begins with Assets. 

In the end I found that it was [getCanonicalPath()](https://github.com/iBotPeaches/Apktool/blob/6d4e503b161d4225bd746a2f218f0130c0de86a3/brut.j.util/src/main/java/brut/util/BrutIO.java#L90) returned the file directory.

The following is a log printout, the assets directory has a file  with the name zipInfo and an Assets directory
![log](https://user-images.githubusercontent.com/9779008/101319238-9f15ed00-389c-11eb-870c-86f4fccec279.png)
