### ISSUE TITLE
Blockers for runing apktool on-device

### ISSUE THREAD

**Issue by WesleyAC** [iBotPeaches/Apktool#2434]
The FAQ mentions that [it's not possible to run `apktool` on-device](https://ibotpeaches.github.io/Apktool/documentation/#faq), since `aapt` doesn't run on android. Is this the only blocker, or are the also other blockers for running apktool on-device? If this is the only blocker, I'd be interested in taking a shot at compiling a version of aapt that can run via the NDK, but if there's significant other work involved, I'd like to know that before futzing too much with trying to cross-compile aapt.

**Comment by iBotPeaches** [comment]
A few repos have spawned up with cross-compiling aapt. The issue is more-so that it won't be officially supported due to the never ending support. We experimented with it, but the building of archs on top of win/mac/linux just became so painful I saw pretty quickly it would never be feasible to maintain long term.

In terms of what is busted. The older version of Android don't have some of the Java7 features we leverage. Now that Java versions go up so fast, I'm sure some of our newer features aren't compatible on Android but I haven't explored any of this to be sure.
