### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by Dakota32** [iBotPeaches/Apktool#2520]
Hello, I'm using Kali Nethunter and I'm trying to use apktool, but every time I'm going to recompile the apk this error:

`brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 131)` 

The problem is to recompile the apk, except that everything is working properly, how can you (creator of apktool) write down this request to solve in the next update?  It is important for Android users that the tool be able to run to `arm`, please, somehow, I really want to use this tool.

**Comment by iBotPeaches** [comment]
> It is important for Android users that the tool be able to run to arm, please, somehow, I really want to use this tool.

Sorry its not on my roadmap. Nor planned.

**Comment by Dakota32** [comment]
> > É importante para os usuários do Android que a ferramenta seja capaz de rodar para armar, por favor, de alguma forma, eu realmente quero usar essa ferramenta.
> 
> Desculpe, não está no meu roteiro. Nem planejado.

Is there no way to solve this?

**Comment by Dakota32** [comment]
> > It is important for Android users that the tool be able to run to arm, please, somehow, I really want to use this tool.
> 
> Sorry its not on my roadmap. Nor planned.

Is there no way to solve this?

**Comment by AndnixSH** [comment]
There are some GUI version of apktool that works on Android. MT manager, and APK Editor Pro have some paid features
APK Repacker seems to be free one

**Comment by Dakota32** [comment]
> There are some GUI version of apktool that works on Android. MT manager, and APK Editor Pro have some paid features
> APK Repacker seems to be free one

It's not as good as apktool, it doesn't do the job exactly as apktool would

**Comment by iBotPeaches** [comment]
> > > It is important for Android users that the tool be able to run to arm, please, somehow, I really want to use this tool.
> > 
> > 
> > Sorry its not on my roadmap. Nor planned.
> 
> Is there no way to solve this?

You are asking for a lot without realizing it. Keeping software working on Android is not the same as keeping it working on any other major OS that is Desktop oriented. First off, we have Java itself. What version of Java is Android? That isn't an easy question because its changed quite heavily over the years. The latest gradle plugin may support Java 8 features by transpile/desugaring changes to lower compatible versions of code, but we aren't building a android application. We are producing a jar and running it on Android.

Have we fixed errors in the past? Sure - we had java.nio incompatibles since we moved to Java 7, but Android caught up. We'd have to limit builds to specific versions to stop complex issues from arising, but even when we think we are done we get an incompatibility with a dependency we use. Do we swap to the Android version of a dependency and hope we can maintain a sane API with the desktop version? What if we can't? Do we make two different builds? Who maintains that? Who supports it when there are milliions of android device pairs out there when you consider root, modding, flashing, beta, etc.

We haven't even spoken about half of Apktool which is the recompilation and as you've learned. Apktool does not do that natively in Java. It drops out to a machine specific binary known as aapt/aapt2 (phasing out aapt1) so we do the same build system as Android apps itself.

Some folks attempted to support ARM based aapt/aapt2 builds but gave up or disappeared. Why? I have no idea, I assume the overhead to maintain something like that version after version with how complex AOSP build systems becomes gets difficult. I know from memory that Apktool aapt builds probably require the following:

 * libz
 * liblog
 * libc
 * libm
 * libstdc++ (tough to static compile at times)
 * libdl
 
You could attempt a non-static build, but that goes against Apktool new ethos that our tool can just be used, since we pack "fat" large aapt binaries so we don't depend on host binaries. Now assuming we decided to do all of that for however many versions of aapt need to be made (hopefully just arm and arm64), since x64/x86_64 is intel I believe. Does Android have any other contenders in that market still? I don't think so, I think the other less known archs dropped out.

So now we attempt to build more binaries on different archs and then have to update Apktool sources to properly detect that and use that binary and open our world to a bazillion different devices and use cases. Who supports that? Who handles the nightmare of support? Someone actually put forward an attempt to do just this, put up very large PRs and I looked at them - then I realized who will update it when they are outdated? Do I have the knowledge to support this? 

So we've come full circle. Its not on the roadmap. Its not something planned. I have more than enough work with handling bugs with our current platforms, integrations and upgrading version of AOSP to even focus expansion.
