### ISSUE TITLE
When will apktool support .aab 

### ISSUE THREAD

**Issue by yanglee0801** [iBotPeaches/Apktool#2576]
Google has imposed restrictions since August .apk files must be submitted using .aab, when will apktool support .aab package related operations

**Comment by iBotPeaches** [comment]
As of right now in my head - never. Apktool works off the base apk and/or any apk in that collection. I'm open to discussing this more if folks feel that aapt2/aapt1 are comparable with bundletool. In my research that appears false, because bundletool works off the built assets from aapt2.

Discussions: https://github.com/iBotPeaches/Apktool/discussions/2572

**Comment by jgmGit** [comment]
@iBotPeaches  why do you think its not compatible ? In the documentation they tell they use aapt2. 

--aapt2=path | Specifies a custom path to AAPT2. By default,&nbsp;bundletool&nbsp;includes its own version of AAPT2.
-- | --

https://developer.android.com/studio/command-line/bundletool

**Comment by jcrabanal** [comment]
There is no need for apktool to directly support AABs. Take in mind this is just an intermediate format for Play Store.
I've managed to automate the following on my tool that makes extensive use of both .APK and .AAB and apktool.

If you wanna use AAB files as an input to apktool:
1. Create a universal APK from it with bundletool bundletool build-apks --bundle=bundle.aab --output=apk_set.apks --mode=universal
2. Open apk_set.apks as a ZIP file, extract universal.apk from it
3. Use apktool with universal.apk to decompile as always

If you want to create an AAB file out of an APK:
1. Decompile the APK with apktool
2. Do your changes
3. If you decompiled the DEX files, recompile them somehow. Not sure how would you do it since I have only used apktool to decompile resources and manifest files.
3. Follow https://developer.android.com/studio/build/building-cmdline#build_bundle to create the bundle using bundletool.
4. Generate a universal APK from your bundle so you can test if everything is okay in your device.

I have managed to fully automate this process without any problem, for a very specific purpose tool I had to develop.

**Comment by AlwaysJoy** [comment]
> There is no need for apktool to directly support AABs. Take in mind this is just an intermediate format for Play Store.
> I've managed to automate the following on my tool that makes extensive use of both .APK and .AAB and apktool.
> 
> If you wanna use AAB files as an input to apktool:
> 
> 1. Create a universal APK from it with bundletool bundletool build-apks --bundle=bundle.aab --output=apk_set.apks --mode=universal
> 2. Open apk_set.apks as a ZIP file, extract universal.apk from it
> 3. Use apktool with universal.apk to decompile as always
> 
> If you want to create an AAB file out of an APK:
> 
> 1. Decompile the APK with apktool
> 2. Do your changes
> 3. If you decompiled the DEX files, recompile them somehow. Not sure how would you do it since I have only used apktool to decompile resources and manifest files.
> 4. Follow https://developer.android.com/studio/build/building-cmdline#build_bundle to create the bundle using bundletool.
> 5. Generate a universal APK from your bundle so you can test if everything is okay in your device.
> 
> I have managed to fully automate this process without any problem, for a very specific purpose tool I had to develop.
> 
> @iBotPeaches may want to implement this, but it is not rocket science, and if you aren't going to do batches for some kind of automation you could just do it manually.
Thank you very much, please ask how to get resources.pb？

**Comment by iBotPeaches** [comment]
I'm currently under the plan to not do anything directly with the AAB format. It is intermediate and at the end of the day an application is made. If AOSP starts accepting AAB directly instead of APK - then perhaps it will be time to revisit.

Locking for the discussion thread - https://github.com/iBotPeaches/Apktool/discussions/2572

@AlwaysJoy - You'll want to read this https://developer.android.com/studio/build/building-cmdline#build_bundle, you can find the answer there during the aapt2 link step.
