### ISSUE TITLE
[FEAT] Autofix for  error: duplicate attribute

### ISSUE THREAD

**Issue by LionisIAm** [iBotPeaches/Apktool#2700]
**Is your feature request related to a problem? Please describe.**
When rebuilding apk without --no-res flag (obviously when you need to modify res) very often I`m getting a lot of errors like
```
W: /res/layout/a0a.xml:2: error: duplicate attribute.
W: /res/layout/a0a.xml: error: file failed to compile.
W: /res/layout/a0e.xml:2: error: duplicate attribute.
W: /res/layout/a0e.xml: error: file failed to compile.
W: /res/layout/a0f.xml:2: error: duplicate attribute.
W: /res/layout/a0f.xml: error: file failed to compile.
W: /res/layout/a0g.xml:2: error: duplicate attribute.
W: /res/layout/a0g.xml: error: file failed to compile.
W: /res/layout/a0h.xml:2: error: duplicate attribute.
W: /res/layout/a0h.xml: error: file failed to compile.
W: /res/layout/a0i.xml:2: error: duplicate attribute.
W: /res/layout/a0i.xml: error: file failed to compile.
W: /res/layout/a0k.xml:2: error: duplicate attribute.
W: /res/layout/a0k.xml: error: file failed to compile.
W: /res/layout/a0l.xml:2: error: duplicate attribute.
W: /res/layout/a0l.xml: error: file failed to compile.
W: /res/layout/a0m.xml:2: error: duplicate attribute.
W: /res/layout/a0m.xml: error: file failed to compile.
W: /res/layout/a0n.xml:2: error: duplicate attribute.
W: /res/layout/a0n.xml: error: file failed to compile.

```
**Describe the solution you'd like**
To fix this we have to manually delete all of this occurrences. 
I think it would be a nice feature in apktool to auto remove everything with duplicates while gathering back sources to an apk.

**Comment by iBotPeaches** [comment]
I don't think that'll solve what you are after. Applications are getting clever and instead of blowing out the name of a key/value pair they are stuffing them with a duplicate name, knowing that Android only cares about the ID.

So if you want to delete duplicates, chances are you may catch some no-op resources that are meant to slow this process down, but at the cost of probably removing many required resources.

I don't see a use-case that is valid for this feature.
