### ISSUE TITLE
[BUG] Resources name

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2749]
### Information
1. **Androlib** - 2.6.0
2. **Android** - 10
3. **Switch Backup** - Google Play

It is necessary to replace resource names with others. Aapt2 does not support some characters including '$'.

### LOG
![Screenshot_20220125-171114.png](https://user-images.githubusercontent.com/31324315/150975402-e1e5a01a-a17e-4cf2-bab2-71caa2780f6d.png)

**Comment by pashamcr** [comment]
There is no apktool/aapt2 for android here.

**Comment by iBotPeaches** [comment]
There are test cases for these exact files - https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/test/resources/aapt2/testapp/res/drawable

This appears to be running Apktool on a device itself. That would mean it must have a different aapt version which is not patched like the ones included in the official releases. I recommend you obtain support with whomever manages Apktool for Android - since it is not me.
