### ISSUE TITLE
[FEAT] aapt binaries for arm

### ISSUE THREAD

**Issue by oSumAtrIX** [iBotPeaches/Apktool#2811]
# Problem

Currently `apktool-lib` has no prebuild binaries for thr arm architecture. This means, that resources can not be compiled on mobile phones.

# Solution

Add pre-built binaries for the arm architecture. Termux currently provides these pre-build binaries and build scripts [here](https://github.com/termux/termux-packages/tree/master/packages/aapt).

**Comment by iBotPeaches** [comment]
The problem is more so signing up to support alternative architectures. I don't plan on moving on this until native AOSP supports it. 

Lodged into Roadmap - https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#android-support

**Comment by Anonymous2716** [comment]
Termuxs aapt doesn't work well yet with apps that was targeted recent android versions (11, 12) .I did a little tweak that allows me to use x86 binaries run on termux.

**Comment by oSumAtrIX** [comment]
@Anonymous2716 would this not require emulation?

**Comment by Anonymous2716** [comment]
@oSumAtrIX yes I did it with qemu-i386. A little slower than native use but not that noticeable.

**Comment by oSumAtrIX** [comment]
> Termuxs aapt doesn't work well yet with apps that was targeted recent android versions (11, 12)

Can you elaborate on that

**Comment by Anonymous2716** [comment]
@oSumAtrIX termux uses its aapt as default with apktool. And every time I use apktool on recent SDK targeted apps it gives me XML build errors . which app doesn't have a lots of XML on res works just fine . 

```
❯ apktool b base -o b.apk
I: Using Apktool 2.6.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/data/com.termux/files/usr/tmp/brut_util_Jar_106390223823776650034599575935767187581.tmp, p, --min-sdk-version, 16, --target-sdk-version, 30, --version-code, 16150060, --version-name, v4.8.1, --no-version-vectors, -F, /data/data/com.termux/files/usr/tmp/APKTOOL2337288095946542186.tmp, -0, resources.arsc, -0, png, -0, arsc, -I, /data/data/com.termux/files/home/.local/share/apktool/framework/1.apk, -S, /data/data/com.termux/files/home/a/base/res, -M, /data/data/com.termux/files/home/a/base/AndroidManifest.xml]
```

**Comment by Anonymous2716** [comment]
@oSumAtrIX  as this https://github.com/termux/termux-packages/blob/master/packages/apktool/aapt-wrapper.patch I call  `qemu-i386 aapt` instead of termux provided aapt. or 64bit your choice . since apktool provides standalone one binary it works. And I compiled apktool from source (v2.6.2) as the instructions given in termuxs repository.  I tried v 2.6.1 gives me errors . I don't recall whice ones. The framework apk apktool provides doesn't seem to resolve all the XML references . a recent update termuxes aapt (android.jar) updated to SDK 31. So I copied android.jar to the path of apktools framework 1.apk. Now I can reverse engineer apps on my phone . and a real device to test on .

**Comment by oSumAtrIX** [comment]
Would modifying the aapt build scripts to use the latest sdk not work?

**Comment by Anonymous2716** [comment]
There are arm binaries that works but couldn't find the source or how to build. Check https://github.com/Hax4us/Apkmod release page . it works in proof.

**Comment by oSumAtrIX** [comment]
> The problem is more so signing up to support alternative architectures

@iBotPeaches We have successfully built aapt2 (and aapt) for several architectures and tested it on android with Apktool and from an Android app:
https://github.com/revanced/aapt2/actions/runs/2373859817

**Comment by eladkarako** [comment]
not sure about aapt

> We built aapt2

useful,  
https://maven.google.com/web/index.html?q=aapt#com.android.tools.build:aapt2:7.4.0-alpha10-8841542 only got builds for osx, win, linux.  

[dist-arm64-v8a](https://github.com/revanced/aapt2/suites/6991776209/artifacts/273850074)
worked well.

**Comment by Anonymous2716** [comment]
@eladkarako your aapt2 binary just prints the help message . not doing anything else.

**Comment by anirudhmalik** [comment]
For anyone still interested in running resource compile (`aapt2`) on device (ARM/Android) rather than only on desktop:

There is now a focused downstream project that does exactly that: [anirudhmalik/apktool-android](https://github.com/anirudhmalik/apktool-android).

It ships static `libaapt2.so` for `arm64-v8a`, `armeabi-v7a`, and `x86_64`, built from the same AOSP/aapt2 lineage as Apktool, with the usual Apktool-oriented patches (and bits layered on top of what [ReVanced/aapt2](https://github.com/ReVanced/aapt2) already carries).
ApktoolAndroid.configure(Context) wires Config so ApkDecoder / ApkBuilder use the extracted binary under nativeLibraryDir, framework cache under the app filesDir, and a real temp dir (not /tmp)—i.e. decode/rebuild in-process inside a normal Android app, not via Termux-only hacks.
Integration, Gradle (AAR + runtime classpath JARs), largeHeap, and useLegacyPackaging for libaapt2.so are documented in [USAGE.md](https://github.com/anirudhmalik/apktool-android/blob/main/USAGE.md).
So the original gap in this issue “no ARM prebuilts in-tree, so you can’t compile resources on a phone the way apktool-lib expects on desktop” is addressed as an Android library, not by extending the desktop JAR layout inside iBotPeaches/Apktool itself.

If maintainers ever want to link this from the main README or close #2811 with a pointer to “community solution: apktool-android,” that would help discoverability; happy to open a small doc PR upstream if useful.
