### ISSUE TITLE
[BUG] APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES

### ISSUE THREAD

**Issue by heyimyunyl** [iBotPeaches/Apktool#2821]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Aptoid

### Stacktrace/Logcat

```
03-19 14:22:36.126: W/GameHelper(15312): ****
03-19 14:22:36.126: W/GameHelper(15312): ****
03-19 14:22:36.126: W/GameHelper(15312): **** APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES
03-19 14:22:36.126: W/GameHelper(15312): **** This is usually caused by one of these reasons:
03-19 14:22:36.126: W/GameHelper(15312): **** (1) Your package name and certificate fingerprint do not match
03-19 14:22:36.126: W/GameHelper(15312): ****     the client ID you registered in Developer Console.
03-19 14:22:36.126: W/GameHelper(15312): **** (2) Your App ID was incorrectly entered.
03-19 14:22:36.126: W/GameHelper(15312): **** (3) Your game settings have not been published and you are 
03-19 14:22:36.126: W/GameHelper(15312): ****     trying to log in with an account that is not listed as
03-19 14:22:36.126: W/GameHelper(15312): ****     a test account.
03-19 14:22:36.126: W/GameHelper(15312): ****
03-19 14:22:36.126: W/GameHelper(15312): **** To help you debug, here is the information about this app
03-19 14:22:36.126: W/GameHelper(15312): **** Package name         : com.ubisoft.dance.JustDance
03-19 14:22:36.126: W/GameHelper(15312): **** Cert SHA1 fingerprint: *****
03-19 14:22:36.126: W/GameHelper(15312): **** App ID from          : *****
03-19 14:22:36.126: W/GameHelper(15312): ****
03-19 14:22:36.126: W/GameHelper(15312): **** Check that the above information matches your setup in 
03-19 14:22:36.126: W/GameHelper(15312): **** Developer Console. Also, check that you're logging in with the
03-19 14:22:36.126: W/GameHelper(15312): **** right account (it should be listed in the Testers section if
03-19 14:22:36.126: W/GameHelper(15312): **** your project is not yet published).
03-19 14:22:36.126: W/GameHelper(15312): ****
03-19 14:22:36.126: W/GameHelper(15312): **** For more information, refer to the troubleshooting guide:
03-19 14:22:36.126: W/GameHelper(15312): ****   http://developers.google.com/games/services/android/troubleshooting
```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

I've decompiled version `3.0.0` of `com.ubisoft.dance.JustDance` and recompiled it with my custom sign. When I launch the APK, the app gets stuck on loading so I wanted to check adb logcat to see what the issue is and I got the error mentioned above. I also tried compressing with original signature thinking maybe it would work and it said `The package appears to be corrupt` while installing.

**Comment by iBotPeaches** [comment]
> 03-19 14:22:36.126: W/GameHelper(15312): **** (1) Your package name and certificate fingerprint do not match
> 03-19 14:22:36.126: W/GameHelper(15312): ****     the client ID you registered in Developer Console.


You resigned it. It no longer matches. The error is saying that. So not sure what Apktool can do here. Closing.

**Comment by heyimyunyl** [comment]
Isn't there some kind of way bypass this? I tried using the original signature and it gave `The package appears to be corrupt`

**Comment by AndnixSH** [comment]
You can only do by creating unsigned APK which will only work on rooted device with disabled signature by LP or Core Patch

https://platinmods.com/threads/how-to-create-unsigned-apk-file-for-rooted-devices-signature-check-disabled-fix-google-fb-login.56347/

**Comment by kursatsaglam** [comment]
English: "The 'APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES' error is typically caused by testing in an emulator environment. This issue is usually not related to the application itself, but rather to the emulator not fully supporting Google Play Games services. Therefore, testing Google Play Games integration on an emulator may lead to inaccurate results. Instead, it is recommended to use Play Console Internal Testing and test the app on a real device. This will provide more reliable and accurate results."

"With kind regards and best wishes." ✨

Turkish: "APP NOT CORRECTLY CONFIGURED TO USE GOOGLE PLAY GAME SERVICES" hatasının temel nedeni genellikle emülatör ortamında yapılan testlerdir. Bu sorun çoğunlukla uygulamadan değil, emülatörün Google Play Games servislerini tam ve doğru şekilde desteklememesinden kaynaklanır. Bu nedenle Google Play Games entegrasyonunu emülatör üzerinden test etmek sağlıklı sonuç vermez. Bunun yerine, Play Console üzerinden Dahili Test (Internal Testing) kullanarak uygulamayı gerçek cihazlarda test etmeniz önerilir. Bu şekilde sorunsuz ve doğru sonuçlara ulaşabilirsiniz."

"Saygılarımla ve iyi dileklerimle." ✨
