### ISSUE TITLE
[FEAT] Better multi dex handling

### ISSUE THREAD

**Issue by Bleuzen** [iBotPeaches/Apktool#2870]
**Is your feature request related to a problem? Please describe.**

Currently apktool creates one smali directory for each dex file from the apk.

This means while adding code to an app the user has to think about the [64k methods limit of dex files](https://developer.android.com/studio/build/multidex#about) and manually count and calculate how much can be still put in which dex file or when a new one has to be created.

**Describe the solution you'd like**

Instead of creating a `smali(_classesN)` dir for each dex, put all smali files into only one directory. Then during build automatically split and generate however many dex files are needed.

As bonus an option to toggle the old (current) behaviour would be nice in case some users don't like it / want to exactly re-construct the original dex files without rearranging classes.

**Additional context**

**Extra**

Have a look at [multidexlib2](https://github.com/DexPatcher/multidexlib2). It even supports multi threading to make the build faster.
But I'm not sure currently if this fits in context of apktool (on smali files directly or would need some workaround / other solution).

**Comment by iBotPeaches** [comment]
I see the need, but in realistic behavior:

 * I can use the api smali/baksmali offers - I cannot re-engineering it.
 * I can't rely on multidexlib2 - its gone 2+ years without work.
 * This would be a large undertaking

**Comment by Morsmalleo** [comment]
I'll second this even know it's been closed as 'not planned'.

My reason for seconding this is because if my understanding is correct, `unsigned short value out of range` errors are thrown by *Apktool* when a modified reverse engineered APK doesn't follow the *64k method limit of DEX files*, and I see this error popping up quite a lot, and in most cases not many people would know how to manually split these up, and simply creating 1 extra `smali_classes#` folder and placing the extra smali files inside here only works for a number of APK files, it doesn't work for all of them.

I've read that Android `buildToolsVersion 22.1.0` and up, have multidex functionality, maybe this could be somewhere to start or maybe it might even fast track the process.

For Apktool to have multidex functionality would be a major stepping stone in my opinion. Please reconsider this @iBotPeaches
