### ISSUE TITLE
[BUG] error: resource android:color/(insert_resource_name_here) not found.

### ISSUE THREAD

**Issue by VenomousSteam81** [iBotPeaches/Apktool#2991]
### Information
1. **Apktool Version (`apktool -version`)** - v2.6.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
@VenomousSteam81 ➜ /workspaces/codespace-vm/testdebug (main ✗) $ apktool b -o mtk-easy-su-v2.1.1-debug.apk output-dir --use-aapt2
I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:22: error: resource android:color/accessibility_focus_highlight not found.
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:25: error: resource android:color/accent_material_700 not found.
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:26: error: resource android:color/accent_material_50 not found.
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:32: error: resource android:color/background_leanback_light not found.
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:55: error: resource android:color/control_nodisable_material not found.
W: /workspaces/codespace-vm/testdebug/output-dir/res/values-v31/colors.xml:61: error: resource android:color/chooser_service_row_background_color not found.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_147206839764744225903007071206539724148.tmp, link, -o, /tmp/APKTOOL11584640055716572443.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 32, --version-code, 208, --version-name, 2.1.1, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /tmp/APKTOOL4824634190021001889.tmp, -0, arsc, -I, /home/codespace/.local/share/apktool/framework/1.apk, --manifest, /workspaces/codespace-vm/testdebug/output-dir/AndroidManifest.xml, /workspaces/codespace-vm/testdebug/output-dir/build/resources.zip]
```

### Steps to Reproduce
1. `apktool b -o mtk-easy-su-v2.1.1-debug.apk output-dir --use-aapt2`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Haven't got that far yet
3. Are you using the latest apktool version? No because latest was giving me issues as well

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to either link/upload the affected apk. Additionally try and provide any logcat and/or stacktrace possible.

**Comment by Vologhat** [comment]
Today, I had a similar problem with this [VK  v8.38](https://play.google.com/store/apps/details?id=com.vkontakte.android) and was able to find a solution for my case.

So, the problem was caused by 2 colors from **values-v31/colors.xml**
`<color name="m3_ref_palette_dynamic_neutral_variant40">@android:color/accessibility_focus_highlight</color>`
`<color name="m3_ref_palette_dynamic_secondary100">@android:color/background_leanback_light</color>`

 **accessibility_focus_highlight** or **background_leanback_light** cannot be found in [android.R.color](https://developer.android.com/reference/android/R.color). This means we can't access those headers at all. The solution is repairing the correct headers. How we can do what? We should to parse resources.arsc, find the [reference ](https://github.com/google/android-arscblamer/blob/2445a3be613e0e0351d0247f173270ca8cd82192/java/com/google/devrel/gmscore/tools/apk/arsc/ResourceValue.java#L37) id values([example](https://imgur.com/a/K4j0baY)) and repair headers by ids using [android.R.color](https://developer.android.com/reference/android/R.color)

PS:
It can be one of tricks to break decompilation, idk.

**Comment by Alaa-HIjazi** [comment]
@Vologhat can you please explain more, i did not understand what you mentioned as a solution.
