### ISSUE TITLE
[FEAT] Standalone QMG extractor

### ISSUE THREAD

**Issue by DexrnZacAttack** [iBotPeaches/Apktool#3096]
**Is your feature request related to a problem? Please describe.**
I am annoyed that there is no standalone QMG decoder/extractor

**Describe the solution you'd like**
This program seems to have one, can someone make a standalone QMG decoder from the source code?

**Additional context**
I am half asleep

**Comment by DexrnZacAttack** [comment]
If this is not applicable to the project, can someone link me to an extractor that would work on a computer, even if it is Linux only?

**Comment by iBotPeaches** [comment]
I think you are confusing what Apktool is doing when it encounters `.qmg` files. It hardly is decoding them - it just parses them as-is as it does not understand the format.

The format also would be an entire library itself with hundreds of hours - probably near 800/1000 to just get the full spectrum working.

Project Zero dug into this format here: https://googleprojectzero.blogspot.com/2020/07/mms-exploit-part-1-introduction-to-qmage.html and you can see the format has basically been around since 2005. It has been versioned over and over so its not as simple as just figuring out the header and hoping its just wrapping a known image format.

This is a format that has been built and proprietary. Apktool can always look at AOSP for tips how to disassemble parts.

The best decoder is just tricking the host Android device to do it for you as seen here: https://forum.xda-developers.com/t/tool-converter-qmg-astc-png.2916486/

So apologies - I am closing this, I don't see this happening.
