### ISSUE TITLE
Decompilation introduces quotes into string resources in res/values/strings.xml

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#315]
Original [issue 204](https://code.google.com/p/android-apktool/issues/detail?id=204) created by ericchubb on 2011-08-11T11:20:18.000Z:

> <b>What steps will reproduce the problem?</b>

Download http://www.freewarelovers.com/android/download/temp/1298727501_Guns-n-Glory_FREE_1.5.1.apk  (too big to attach to the bug)
1. Decompile the APK file using apktool v1.4.1
2. browser to the &quot;res/values/strings.xml&quot;
3. There is a string with the text &quot;Did you hear that terrible crash in the mountains.&quot;
4. In version 1.4.1 of apktool, the string has quotes at the beginning and end of the text. In version 1.3.1, it did not. These quotes are visible in the text in the running application post-recompilation, and look like they shouldn't be there.

**Comment by AnnMarieE** [comment]
I understand was this was closed as the issue is still present in the current version.
The addition of the quotes in the strings.xml file can been seen in the running APK file, however I believe that it is only strings which have character escaping in the text which is the problem.
For example these are the original strings in the version 1.3.1:
Guns\'n\'Glory
Hey Boss! It\'s Pedro! We\'ve spotted a few of these settlers coming through the canyon! You should send a Desperado out there! Remember, you can also deselect him again and leave him standing out in the sun if you press the Action key!

Which are now the following after an initial unpacking:
"Guns'n'Glory"
"Hey Boss! It's Pedro! We've spotted a few of these settlers coming through the canyon! You should send a Desperado out there! Remember, you can also deselect him again and leave him standing out in the sun if you press the Action key!"

Why have these quotes now become part of the segment as they are left there and are visible in the running version of the software? 

![apk quotes - v1 3 1 vs v2 0](https://cloud.githubusercontent.com/assets/11993354/7201424/c8cd6a94-e4fe-11e4-9f86-a624b1490999.png)
![apk v2 0 - no quotes](https://cloud.githubusercontent.com/assets/11993354/7201425/c8cfccd0-e4fe-11e4-9b5c-cedd45e21ff3.jpg)

**Comment by iBotPeaches** [comment]
I was under the impression these two strings were the same.

```
Guns\'n\'Glory
```

```
"Guns'n'Glory"
```

One forces you to escape characters while the other doesn't. The double quotes shouldn't be there though in the final apk. Since you provided some example strings, I will add them to our unit-tests and see what we are dealing with.

**Comment by AnnMarieE** [comment]
Great thanks. The last screenshot shows an example of a really long string, but as it appears there is no escaping necessary within the segment, then no quotes are added to this one.

**Comment by AnnMarieE** [comment]
Can you please tell me if you have evaluated this issue? 
Currently it is a blocker for us in upgrading to the latest version of the APKTool.exe.

**Comment by iBotPeaches** [comment]
I have not, its pretty low priority compared to some other bugs. Sorry!

**Comment by Pat-15** [comment]
We see this problem too, see attached screenshot which shows installation of original Whatsapp app vs. installation of Whatsapp decompiled and recompiled with current Apktool.  This issue has been present since 1.4.1 and unfortunately we have to stay on 1.3.1 until it is fixed.
![orig vs new](https://cloud.githubusercontent.com/assets/11993706/7318266/dad42b5a-ea81-11e4-9e62-93acf9a0adae.gif)

**Comment by iBotPeaches** [comment]
![Screenshot_20230730-114038](https://github.com/iBotPeaches/Apktool/assets/611784/79cd59a0-712d-4f40-a6a6-83c3c20f47fc)

I know this is honestly 7 years old and useless to even respond, but I took the effort to download the original application and tested it with a basic launch. That photo is above.

I then decoded and re-assembled with no changes.

```
➜  315 apktool d 315.apk 
I: Using Apktool 2.8.2-22eb80-SNAPSHOT on 315.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  315 apktool b 315 --use-aapt2
I: Using Apktool 2.8.2-22eb80-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 315/dist/315.apk
➜  315 
```

Re-launched and went back to same place.

![Screenshot_20230730-121139](https://github.com/iBotPeaches/Apktool/assets/611784/ea53d93b-10b6-461b-ab68-3a690950b033)

This seems all right now. I'm guessing either our styled rewrite or something resolved this. Sorry for ignoring for almost a decade.

Closing.
