### ISSUE TITLE
Cannot run in the cli at all

### ISSUE THREAD

**Issue by viren-joshi** [iBotPeaches/Apktool#3418]
### Information
1. 2.9.0
2. Linux (Ubuntu)
3. None
4. 8 -

I cannot run the command at all, I followed the steps in the website to install the tool but when i run the command
```
apktool
```
it gives me the following output
```
/bin/ls: cannot access '': No such file or directory
/usr/local/bin/apktool: line 1: cygpath: command not found
/usr/local/bin/apktool: line 1: payload:allShortcutsEnabled:false: command not found
```

I am very much unaware of how this exactly works, I tried fixing the script but it didn't really help.
I dont know if this is a bug or some issue on my part. Please help me out.

**Comment by iBotPeaches** [comment]
Apologies. It looks like something odd went on. Its not a bug as you imagine because it works on unix machines for thousands of others.

Nor do I have an idea of what you can check. I would recommend though if you are unaware of how to run/install a java application - you may be attempting to run a complex piece of software (reverse engineering) without fully understanding what is happening.

Let me know if you figure out what it was though to help future searchers.
