### ISSUE TITLE
[BUG] unexcepted space char in AndroidManifest.xml

### ISSUE THREAD

**Issue by meilaopo** [iBotPeaches/Apktool#3437]
decode my apk, got unexcepted space char in AndroidManifest.xml
while I open the apk in Android Studio, the xml is correct

decoded xml:

![WXWorkCapture_17008312131716](https://github.com/iBotPeaches/Apktool/assets/59859171/95ae3f78-02fe-4392-a669-5aa675740590)

android studio:
![WXWorkCapture_17008315388938](https://github.com/iBotPeaches/Apktool/assets/59859171/7b134442-597a-4f79-b629-fbdcc0900ba4)

**Comment by iBotPeaches** [comment]
This was a needed workaround for aapt1 to treat the numbers as a string, otherwise it would treat them as numeric then overflow and be wrong.

This isn't needed for aapt2, but we don't know aapt2/aapt1 during disassembly when this is changed. This is why this bug exists: https://github.com/iBotPeaches/Apktool/issues/2634

So closing for duplicate.
