### ISSUE TITLE
Missing uses-sdk tag in manifest

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#828]
Original [issue 719](https://code.google.com/p/android-apktool/issues/detail?id=719) created by odexcide on 2014-12-03T15:48:32.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. Decompile an apk that is known to contain a &lt;uses-sdk&gt; tag in the AndroidManifest.xml.
> 2. Compare &quot;aapt dump badging &lt;file.apk&gt; | grep sdk with apktool's generated AndroidManifest.xml

<b>What is the expected output? What do you see instead?</b>
The &lt;uses-sdk&gt; tag should be present in the AndroidManifest.xml file and it is not there.

<b>What version of the product are you using? On what operating system?</b>
apktool-1.5.2 and apktool-2.0.0rc3

**Comment by edermi** [comment]
I was wondering if there is any technical reason for omitting nodes of the AndroidManifest.xml apart from being redundant information because it is also stored in apktool.yml. I did a little bit of research and understand that there are some places where storing the information outside of the Manifest is required and I'm absolutely fine with that. Some users (like me) use apktool to get the human-readable version of the AndroidManifest to further work with it. Missing nodes is an unexpected behaviour and getting the complete XML is - according to numerous bugreports regarding this or related issues - something users are sometimes looking for.

Would generating the complete AndroidManifest.xml break other apktool functionality? If not, I suggest adding the <uses-sdk> and other omitted information to the AndroidManifest.xml.

**Comment by iBotPeaches** [comment]
During build, `aapt` requires the version information to be passed via parameter as `--version-code` and `--version-name`. If a value exists in the `AndroidManifest.xml`, then that value in prior versions of `aapt` halted the build, due to already existing. I believe in the current version of `aapt`, it just says "Value already exists, ignoring." Or something to that affect.

If you require a 100% match of the original and **DON'T** plan on rebuilding. You may find using `-m`. This is for "matching original", for researchers, etc. It matches the apk, leaving any elements in, but usually prevents rebuilding as all the required changes are not preformed. This will leave your SDK information in the manifest.

**Comment by edermi** [comment]
`-m` works as intended, thanks a lot for pointing this out!
