### ISSUE TITLE
Error parsing XML: not well-formed (invalid token)

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#885]
Original [issue 776](https://code.google.com/p/android-apktool/issues/detail?id=776) created by kefir500 on 2015-03-04T10:57:38.000Z:

> <b>What steps will reproduce the problem?</b>
> - Download and recompile this APK: https://www.dropbox.com/s/916e1t25k6notia/locus.apk?dl=1

<b>What is the expected output? What do you see instead?</b>

```
warning: string 'pref_map_show_center_cross' has no default translation.
warning: string 'pref_map_show_center_cross_desc' has no default translation.

C:\Apktool\res\layout\abc_action_menu_layout.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Apktool\res\layout\abc_action_mode_bar.xml:2: error: Error parsing XML: not well-formed (invalid token)

C:\Apktool\res\layout\abc_activity_chooser_view.xml:2: error: Error parsing XML: not well-formed (invalid token)
```

--- And 5 more similar errors ---

```
C:\Apktool\res\layout\fragment_track_record.xml:24: error: No resource identifier found for attribute 'pw_text' in package 'android'

C:\Apktool\res\layout\fragment_track_record.xml:24: error: No resource identifier found for attribute 'pw_textSize' in package 'android'

C:\Apktool\res\layout\fragment_track_record.xml:24: error: No resource identifier found for attribute 'pw_barColor' in package 'android'
```

-- And &gt;10 similar errors ---

```
C:\Apktool\res\layout\view_color_picker_basic_tab.xml:5: error: Error parsing XML: duplicate attribute
```

<b>What version of the product are you using? On what operating system?</b>
- Apktool RC4
- aapt.exe (from the Apktool GitHub repository)

<b>Please provide any additional information below.</b>
Seems that XML tags are corrupt. Tried to fix these XML tags manually - no luck. Also tried different aapt and Apktool releases - still the same. Removing &quot;framework/1.apk&quot; does not help.

**Comment by ddccffvv** [comment]
Would it be possible to work around this by just renaming the classes to unique [a-Z*] names and updating the references (during/after decompilation)?

**Comment by jack16099** [comment]
Is this issue fixed? I think I've seen some modded apps which gives the same error on latest version of apktool and there's those illegal  characters in the manifest. If I'm not wrong that it's modded, how did they do it if apktool can't?

**Comment by warren-bank** [comment]
though this issue is closed, I recently encountered this behavior with apktool 2.4.1

to summarize, the problem traced back to the fact that the decoded apk contained smali filenames with unicode characters.

as a workaround, I wrote a small [nodejs command-line utility](https://github.com/warren-bank/node-remap-apktool-unicode-filenames) to rename all smali unicode filenames, and remap all references elsewhere in the project.

wrote it in a day.. might not solve everyone's woes, but I hope that some may find it useful; worked for me.

**Comment by pgp** [comment]
Same issue here, I tested the same apk (titanium backup 7.6.0.1) linked in https://github.com/iBotPeaches/Apktool/issues/1389 , using apktool 2.5.0 ... Gonna try @warren-bank script for now

**Comment by warren-bank** [comment]
I'm in a virtualized environment right now, so I can't check my notes (on modding TB) until later.. but I do remember TB having some unique issues. I believe that more recent versions decompile with missing resource directories, in addition to unicode issues. I had to iteratively test older versions until I found the last one to decompile without any missing resource directories. It was that version that I was able to successfully round-trip: decompile, (optionally) modify smali source files, run my script, recompile, and run in Android without any installation or runtime errors.

**Comment by pgp** [comment]
Actually, on another apk that had this issue, I managed to make recompile work (and also to correctly run on the emulator the recompiled apk after resigning it) by replacing: `<id ` with: `<item type="id" ` in the `res/values/ids.xml` file.
On the above mentioned titanium backup apk, the inconsistent files I edited so far using this strategy are:
```
res/values/ids.xml
res/values/layouts.xml
res/values/drawables.xml
```
but now apktool complains about `res/values/colors.xml`, it seems because in this case the xml tag has no content (apart from the name property).
Still, it is unclear to me why apktool generates these xml files with inconsistent schema.

Disclaimer: what I'm trying to do is recompiling some apks I don't trust, after having removed INTERNET permission from manifest (this avoids the burden of installing 3rd party firewalls for having the same functionality, since android doesn't have a decent way of providing firewall feature at the OS level)

**Comment by warren-bank** [comment]
As an aside.. we should really set up some kind of repo:
* with a branch for each:<br>`${apk_package_id}/${apk_version_code}/${apk_sha1_hash}/${apktool_version}`
* and share our patched smali files
* or better yet..
  * just diffs
  * since apktool output is deterministic given:
    * identical input apk files
    * identical versions of apktool
  * and identical apk files can be guaranteed by SHA1 hash

I don't know about any of you, but:
* I'd never run an apk that isn't signed by its original author
  * which rules out running apks modded by anyone other than myself
* I'm sitting on a huge database of diffs that I'd be willing to share
  * which would allow others to apply my exact same changes to a trusted/original version
* I _really_ don't want to get into any kind of legal trouble for doing so..

**Comment by pgp** [comment]
Actually, I started experimenting with apktool just for curiosity, so that when I found those apk that gave errors during recompilation, I also tried to reproduce this by using an obfuscation dictionary in proguard rules in one application of mine: I thought these errors were due to usage of non-ascii characters in proguard mappings, yet the apk generated for my application decompiled and recompiled fine even with the proguard rules modification.
Now I'm even more curious to know how to reproduce this scenario in my source code, so any hint of possible proguard settings responsible of this issue is welcome.

**Comment by pgp** [comment]
BTW: you were talking about modifying smali files, it's clearly not my case, so this issue should be related to something else at least.
