### ISSUE TITLE
install shared library apks

### ISSUE THREAD

**Issue by duanqz** [iBotPeaches/Apktool#931]
how to install more than 2 shared library apks?

when I use the following commands:

```
apktool if shareLibrary1.apk
apktool if shareLibrary2.apk
```

it shows: 

```
I: Framework installed to: /home/duanqizhi/apktool/framework/2.apk
I: Framework installed to: /home/duanqizhi/apktool/framework/2.apk
```

it is confused when I decode an apk that using these two shareLibrary apks:

```
I: Using Apktool 2.0.0 on SharedLibraryClient2.apk
I: Loading resource table...
I: Decoding Shared Library (com.google.android.test.shared_library), pkgId: 2
I: Decoding Shared Library (com.google.android.test.shared_library2), pkgId: 3
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/duanqizhi/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: /home/duanqizhi/apktool/framework/2.apk
I: Decoding values */* XMLs...
Can't find framework resources for package of id: 3. You must install proper framework files, see project website for more info.
```

You see this:
both shareLibrary are installed to be pkg id 2, but when I decoded an apk, it try to decode an shared Library of pkg id 3, which lead to decode failure

**Comment by BurgerZ** [comment]
Could you upload apk files for tests?

**Comment by iBotPeaches** [comment]
Yeah, as @BurgerZ said, upload all the apks with this (frameworks, etc).

I don't believe Shared Frameworks have dependencies on resources, like you think here. It is just a coincidence that the shared framework is depending on a `pkgId` of `3`, which is not installed.

**Comment by duanqz** [comment]
You could find all the apk files out by link: https://github.com/duanqz/holder.

* SharedLibrary.apk and SharedLibrary2.apk are two different shared libraries I make out.
* SharedLibraryClient.apk is an normal apk which depends on both the two shared libraries.

I could not decode SharedLibraryClient.apk, even if I have install frameworks by typing:
   [apktool if shareLibrary1.apk && apktool if shareLibrary2.apk]
error report is "Can't find framework resources for package of id: 3."

After inspecting the source code,  I have found in ARSCDecodeer.readPackage(), simple handle shared library by this:
        if (id == 0) {
            // This means we are dealing with a Library Package, we should just temporarily
            // set the packageId to the next available id . This will be set at runtime regardless, but
            // for Apktool's use we need a non-zero packageId.
            // AOSP indicates 0x02 is next, as 0x01 is system and 0x7F is private.
            id = 2;
            mResTable.setSharedLibrary(true);
        }

It is bad, almost all the oem vendors ,like htc, sasumg, have their own resources, their resource's id spec might be 0x02.

**Comment by iBotPeaches** [comment]
There is no good solution for this. `aapt` has all frameworks passed to it during runtime, so it can easily determine that there is already a shared library at `0x02`, it then increments to `0x03`. Sadly, every apktool run is independent of the last, with no memory between them.

If we install `SharedLibrary.apk`, it installs to `~/home/apktool/framework/2.apk`. We would need to adapt this check to install the shared library with a `tag` so we know it was a shared library and not just a regular ole framework. This would allow the 2nd apk (`SharedLibrary2.apk`) to identify this file at `2-tag.apk` and set its `pkgId` to `previous pkgId++`. Then it would be stored as `3-tag.apk`.

Then decoding the application with `-t tag` would work. However, there are major problems with this approach. All future shared decodes with the same tag would immediately install as `3.apk`, because the `pkgId` of `2` is taken. The tag would have to be unique from each `apk`, much like the `packageName`.

However, this has grown from a simple problem to a huge one. Our current apktool has no knowledge of scanning available frameworks in order to do the detection required for this change.

Also, since I can't find any true documentation on this new `--shared-lib` feature, I'm hesitant to say whether two libraries are even allowed. None of the applications that use this feature in AOSP or popular OEMs have two Shared Libraries. The only time I've ever seen two, is this apk you made up.

Sadly, I think this will just have to be put on the backburner until
 
1. Applications start utilizing two shared libraries, thus bumping priority
2. An easier solution is discovered
3. I encounter a lot of free time

**Comment by duanqz** [comment]
Thanks a million.

I knew that the using --tag or --framework-path can distinguish installed shared libraries, and build back with --framework-path.

You are right that the shared resource ID is determined at runtime, and "<framework-path>/2<-tag>.apk" could handle the case that each apk only use one shared library. 

I still expect installing shared libraries by increasely ID, start with a large number, like 17, instead of 2,
which will not conflict with OEM vendor's resource APK.

**Comment by iBotPeaches** [comment]
5 years on back-burner. Nothing is going to happen here. Not feasible in any sane timeline. Closing.
