### ISSUE TITLE
Visual issues after recompiling

### ISSUE THREAD

**Issue by dezmen3** [iBotPeaches/Apktool#932]
Greetings, got this weird bug when i'm recompiling apk and some menus just vanishing, even without doing any changes. Tried pretty much all apktool versions up to 2.0.0. Seems Xiaomi did something new to compile their Mi Fit app. No errors on compiling what so ever.
App:
http://app.mi.com/detail/68548
or
https://www.sendspace.com/file/i1uqmo

![1](https://cloud.githubusercontent.com/assets/7240960/7421093/7b0dcdf8-ef8a-11e4-8af0-1c6961bc4365.png)
![2](https://cloud.githubusercontent.com/assets/7240960/7421094/7b26786c-ef8a-11e4-86ef-170106ba5a8e.png)

**Comment by IaguCool** [comment]
I think it's related to #934

**Comment by iBotPeaches** [comment]
I followed this pattern.

`apktool d MiFit_1.4.452_1050.apk`
`apktool b MiFit_1.4.452_1050 -o dirty.apk`
`apktool d dirty.apk`

Then compared the decoded folders. I had no differences. If I can't find any differences between the original decoded application and the rebuilt decoded application, than that means an error would have to occur during the initial decompilation of the original apk to source.

Can't really find anything to investigate and due to the nature of large scale applications like this its nearly impossible to track down a problem like this. If you can somehow create a test application that experiences this behavior that would save me tons of time. 

Currently with the already confirmed list of bugs, this issue might be on the backburner for a bit. Sorry!

**Comment by dezmen3** [comment]
I've tested with different frameworks of MIUI i.e 4.4.2, 4.4.4 and 5.0.2. Same result. But I can tell, Xiaomi packs it with 4.4.4 framework and below due to no v4/v13 parts in apk. After releasing new apk in market, nothing changed, same vanishing of menu. Problem is more like on decompiling stage, because after compiling and decompiling again - files seems same.

**Comment by iBotPeaches** [comment]
I checked all the qualifiers with (`aapt d configurations MiFit.apk`), then decoded it. All the qualifiers listed via `aapt` were present in the decode. Not sure where the error is occurring yet.

**Comment by dezmen3** [comment]
Originaly app checks if you run MIUI v5 or v6 and decides if it will show you that menu and activate it. Maybe its somehow connected with this issue.

**Comment by BurgerZ** [comment]
This is not issue.
These menu items (alarm, sms notifications) are both present at menu and are absent after recompilation, because of app signature. I've researched that this features need this permission:
```
miui.permission.BLE_IMMEDIATE_ALERT
```
But this permission has signatureOrSystem protection level:
```
<permission android:name="miui.permission.BLE_IMMEDIATE_ALERT" android:protectionLevel="signatureOrSystem"/>
```
So if you recompile this app - you will loose these menu items. 
Try to place your apk in /system/app folder and you will see that these items will be present in menu.

So this is NOT an issue.

**Comment by Acid-miuipolskapl** [comment]
I tested that. Placed app in system/app + added missing libs from apk to system/lib.
App works but no menu items. Altough my app is signed with platform key.

**Comment by Acid-miuipolskapl** [comment]
I tested all keys and still it doesnt work.

**Comment by BurgerZ** [comment]
"SMS notifications" menu item:
![image](https://cloud.githubusercontent.com/assets/1331650/7608184/e48ac35a-f96f-11e4-9246-5279d68cf862.png)

**Comment by Acid-miuipolskapl** [comment]
Ok but how? I tested also removing android:protectionLevel or setting it to "normal"

**Comment by BurgerZ** [comment]
The app itself compares it's signature hash form the source code. If signature hash stored in code is not equal to the package signature, these menu items become hidden (from code)

**Comment by Acid-miuipolskapl** [comment]
But MIUI uses testkey (and recently platform in patch rom) for system apps.
Neither of these works. Or I have them outdated... And you suggest also leaving protectionLeven "signagureOrSystem" or "normal"?

**Comment by IaguCool** [comment]
Well, when I modded some system apps on my Xperia Z1, I couldn't get them to work because there's a signature checking happening in "framework/services.jar" in smali\com\android\server\pm\PackageManagerService.smali function compareSignatures([Landroid/content/pm/Signature;[Landroid/content/pm/Signature;)I
When I edited the function, signature checking always returned 0 (signature are not different) and every system app I modded works perfectly.

**Comment by BurgerZ** [comment]
@IaguCool that's an option for private use, but if you are a community which provides roms for public, you shouldn't open such a huge security hole.

**Comment by IaguCool** [comment]
That's the only option if you want custom system apps. Unless you want to be stuck on a bootloop. System apps aren't meant to be modified.

**Comment by iBotPeaches** [comment]
You all can continue this conversation, I don't mind, but it appears that MiBand & its associated OEM have taken additional steps to prevent a simple decode of their application.

Since there still isn't any logs or proof that Apktool is at fault, I am going to close this.

Thanks @BurgerZ for investigating this.

**Comment by Acid-miuipolskapl** [comment]
The most probably solution for this is that signature verification as recompiled app doesnt have any changes between decompiled at first. So there has to be another process that hides options. 
Weird is that I already patched signatureCompare method to return 0 and it should work, but it doesn't...

**Comment by Acid-miuipolskapl** [comment]
@IaguCool:
We dig in MIUI system apps all the time. Doing sometiimes heavy modifications for our needs. It always worked. The best is that we also used to have modded MiFit app from en.miui.com (made by russians) and they had that sms notification mod included. Now once Xiaomi developed same thing it doesn't work because of those stupid permissions issue.
