### ISSUE TITLE
Error Compile Setting.apk miui base on lollipop

### ISSUE THREAD

**Issue by igobig** [iBotPeaches/Apktool#965]
error in below

```
T:\Desktop\apktoo>apktool if Settings.apk
I: Decoding Shared Library (miui), pkgId: 8
I: Decoding Shared Library (android.miui), pkgId: 9
I: Framework installed to: C:\Users\miuidev\apktool\framework\127.apk
```
```
T:\Desktop\apktoo>apktool d Settings.apk
I: Using Apktool 2.0.0 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 8
I: Decoding Shared Library (android.miui), pkgId: 9
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\miuidev\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\miuidev\apktool\framework\8.apk
I: Decoding Shared Library (androidhwext), pkgId: 7
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\miuidev\apktool\framework\9.apk
I: Decoding Shared Library (miui), pkgId: 8
W: Could not decode attr value, using undecoded value instead: ns=android, name=
text, value=0x09070051
W: Could not decode attr value, using undecoded value instead: ns=android, name=
text, value=0x0907004f
W: Could not decode attr value, using undecoded value instead: ns=android, name=
text, value=0x09070050
W: Could not decode attr value, using undecoded value instead: ns=android, name=
text, value=0x0907004f
W: Could not decode attr value, using undecoded value instead: ns=android, name=
text, value=0x09070050
W: Could not decode attr value, using undecoded value instead: ns=android, name=
keyBackground, value=0x090200a7
W: Could not decode attr value, using undecoded value instead: ns=android, name=
keyBackground, value=0x090200a7
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x090a000e
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResRefe
renceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResSc
alarValue.java:57)
        at brut.androlib.res.data.value.ResScalarValue.serializeToResValuesXml(R
esScalarValue.java:74)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:496)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

T:\Desktop\apktoo>
```
setting.apk file
https://drive.google.com/file/d/0B3QXBNjbkCgrRVJfMW1QaTBlS2s/view?usp=sharing

**Comment by BurgerZ** [comment]
Just look at my response here:
https://github.com/BurgerZ/jBART/issues/94

**Comment by igobig** [comment]
@BurgerZ  thanks for guide issue fix it.

**Comment by vagyula1** [comment]
I can't compile the framework files. (Mi4i)
https://drive.google.com/file/d/0B3T0RlCvTtOqdERDOGZDc20tRDg/view?usp=sharing
Framework files installed
apktool if framework-res.apk
apktool if framework-ext-res.apk
apktool if miui.apk
apktool if MiuiFramework.apk

apktool d MiuiFramework.apk
c:\apktool>apktool d framework-ext-res.apk
I: Using Apktool 2.0.0 on framework-ext-res.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 8
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Tulajdonos\apktool\framework\1.apk

I: Renamed manifest package found! Replacing com.miui with com.android.miui
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

c:\apktool>apktool b framework-ext-res
I: Using Apktool 2.0.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_auto_active.xml
:2: error: Error: No resource found that matches the given name (at 'id' with va
lue '@id/status_bar_toggle_sync_active').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_auto_active.xml
:4: error: Error: No resource found that matches the given name (at 'drawable' w
ith value '@drawable/status_bar_toggle_sync_auto_active_0').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_auto_active.xml
:5: error: Error: No resource found that matches the given name (at 'drawable' w
ith value '@drawable/status_bar_toggle_sync_auto_active_1').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_auto_active.xml
:6: error: Error: No resource found that matches the given name (at 'drawable' w
ith value '@drawable/status_bar_toggle_sync_auto_active_2').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_auto_active.xml
:7: error: Error: No resource found that matches the given name (at 'drawable' w
ith value '@drawable/status_bar_toggle_sync_auto_active_3').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_manual_active.x
ml:2: error: Error: No resource found that matches the given name (at 'id' with
value '@id/status_bar_toggle_sync_active').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_manual_active.x
ml:4: error: Error: No resource found that matches the given name (at 'drawable'
 with value '@drawable/status_bar_toggle_sync_manual_active_0').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_manual_active.x
ml:5: error: Error: No resource found that matches the given name (at 'drawable'
 with value '@drawable/status_bar_toggle_sync_manual_active_1').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_manual_active.x
ml:6: error: Error: No resource found that matches the given name (at 'drawable'
 with value '@drawable/status_bar_toggle_sync_manual_active_2').

c:\apktool\framework-ext-res\res\drawable\status_bar_toggle_sync_manual_active.x
ml:7: error: Error: No resource found that matches the given name (at 'drawable'
 with value '@drawable/status_bar_toggle_sync_manual_active_3').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\TULAJD
~1\AppData\Local\Temp\brut_util_Jar_8146025564658864623.tmp, p, --forced-package
-id, 9, --min-sdk-version, 21, --target-sdk-version, 21, --rename-manifest-packa
ge, com.miui, --version-code, 21, --version-name, 5.0.2-V6.5.6.0.LXIMICD, -F, C:
\Users\TULAJD~1\AppData\Local\Temp\APKTOOL6694047727765453022.tmp, -x, -0, arsc,
 -I, C:\Users\Tulajdonos\apktool\framework\1.apk, -S, c:\apktool\framework-ext-r
es\res, -M, c:\apktool\framework-ext-res\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        at brut.androlib.Androlib.buildResources(Androlib.java:396)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\TULAJD~1\AppData\Local\Temp\brut_util_Jar_8146025564658
864623.tmp, p, --forced-package-id, 9, --min-sdk-version, 21, --target-sdk-versi
on, 21, --rename-manifest-package, com.miui, --version-code, 21, --version-name,
 5.0.2-V6.5.6.0.LXIMICD, -F, C:\Users\TULAJD~1\AppData\Local\Temp\APKTOOL6694047
727765453022.tmp, -x, -0, arsc, -I, C:\Users\Tulajdonos\apktool\framework\1.apk,
 -S, c:\apktool\framework-ext-res\res, -M, c:\apktool\framework-ext-res\AndroidM
anifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\TULAJD~1
\AppData\Local\Temp\brut_util_Jar_8146025564658864623.tmp, p, --forced-package-i
d, 9, --min-sdk-version, 21, --target-sdk-version, 21, --rename-manifest-package
, com.miui, --version-code, 21, --version-name, 5.0.2-V6.5.6.0.LXIMICD, -F, C:\U
sers\TULAJD~1\AppData\Local\Temp\APKTOOL6694047727765453022.tmp, -x, -0, arsc, -
I, C:\Users\Tulajdonos\apktool\framework\1.apk, -S, c:\apktool\framework-ext-res
\res, -M, c:\apktool\framework-ext-res\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:413)
        ... 6 more

What's wrong?
