### ISSUE TITLE
bug in apktool v2.0.0 command line parser

### ISSUE THREAD

**Issue by Lanchon** [iBotPeaches/Apktool#970]
the --advanced help states this:

```
usage: apktool [-q|--quiet OR -v|--verbose] d[ecode] [options] <file_apk>
    --api <API>                    The numeric api-level of the file to generate, e.g. 14 for ICS.
usage: apktool [-q|--quiet OR -v|--verbose] b[uild] [options] <app_path>
 -a,--aapt <loc>         Loads aapt from specified location.
```

however the tool does not recognize an --api # option.

this fails to parse:

> apktool d --api 15 ...

and this parses ok:

> apktool d -api 15 ...

but so does this:

> apktool d -api YGWYWD ...
> apktool d -aOJIDD IUIUDW ...
> apktool d -aOJIDD ...

and this, which are options for build, not decode:

> apktool d --aapt YGWYWD ...
> apktool d --copy-original ...

and this complaints about missing argument to '-a':

> apktool d --aapt ...

i think that the --api option, by not having a short version, somehow conflicts with --aapt due to the automatic option shortening behavior. (i -api is probably being parsed as -aapt pi.)

more importantly, the options for build should not be parsed when invoking decode, etc, but this is obviously a shortcut that you decided to take:
https://github.com/iBotPeaches/Apktool/blob/v2.0.0/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L57

the problem is that allOptions is malformed and cannot be used. it contains several instances of different options for which the short option is the same, breaking the input invariant to the parser, and thus the parser is liable to fail (as it is happening).

of course the right solution would be to parse selectively on the first argument, because it is too late to change the short options now.

as a stopgap fix you could set short options for the options without (eg: uppercase A for --api) and see what happens. (bug waiting to happen again!)

yet another route is this: commons CLI 1.3 has been released after many years and all parsers have been deprecated in favor of DefaultParser.

```
A new parser is available: DefaultParser. It combines the features of the
GnuParser and the PosixParser. It also provides additional features like
partial matching for the long options, and long options without
separator (i.e like the JVM memory settings: -Xmx512m). This new parser
deprecates the previous ones.
```

https://apache.googlesource.com/commons-cli/+/trunk/RELEASE-NOTES.txt

it is possible that the new parser fixes this issue, but it might break in some other way since you are giving it an invalid option set to start with.

maybe you can:
1) create a pre-command option group
2) parse asking the parser to stop at first non-option
3) consume the first remaining argument, check for command word
4) pick the right option group for the command (setting advanced=true for its generation)
5) parse the remaining arguments
6) fuse the results of 2) and 5) (or later check each option in the collection it belongs)

**Comment by raziel23x** [comment]
New (Apktool 2.0.x) command line commands ..........
apktool if framework-res.apk -t tag
apktool d framework.res.apk -o output
apktool b output -o new.apk

**Comment by Lanchon** [comment]
yes I know, my report applies to v2.0.0. so what is the relevance?

**Comment by iBotPeaches** [comment]
Yeah I see the problem here. The way we are currently programmed, doesn't leave an option to selectively setup the Parser. Its all options or none.

I see how to fix that, but the reworking necessary is not worth the allocation of my time. I tried simply moving the option to `API` instead of `api`, same error. Same with `api-level`. Not sure why this is happening because then the conflict should also be happening with `frame-path` and `frame-tag`. However, it doesn't. 

It must have to do with options that only have a long code and no short code. Either way, yes I duplicate.

**Comment by Lanchon** [comment]
a few comments:

-with the malformed collection of options you pass in, the parser is free to do anything at all. no specific functionality should be expected. it is a dangerous situation, more bugs like this could be lurking.

-you really shouldn't change the command line syntax! many tools depend on apktool already, it'd be the worst solution. after such a change, other tools would need to be forked for before and after versions of apktool, it'd be a whole mess.

-as i mentioned, you can probably fix the 'api' issue by adding a short option (say 'A') and without breaking compatibility. still, the options would remain malformed and parsing would not be guaranteed.

-on 'frame-path': you have several identical options including the short op. the parser chooses one to populate when parsing. if the getter also chooses the same instance, it works. otherwise the options you pass in are swallowed into limbo and never reach the tool.

 and 'frame-tag' and 'tag': both use the short option 't'. there is clearly another bug here. the parser has two places to put the passed argument in, while the code gets it from one:
https://github.com/iBotPeaches/Apktool/blob/v2.0.0/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L126
https://github.com/iBotPeaches/Apktool/blob/v2.0.0/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L238
both use getter with argument 't'. so when you use the long options in the command line
-for one of them, the tool sees the value passed in set IN BOTH OPTIONS.
-for the other, the value goes to limbo and the tool never sees it.
if you use the short option its the same: the value either it gets into both options or in none.

there could be other bugs. unbounded.

**Comment by iBotPeaches** [comment]
I was simply changing them for testing. Since apktool follows semver, I cannot change option snytax unless I label the release as `2.1` which I have no plan on doing. I'm always open for pull requests :p

**Comment by Lanchon** [comment]
i'd do it if i could. but this has no impact on my project for now and i have very little time. :(

**Comment by iBotPeaches** [comment]
2 years later, but I finally looked into fixing this due to the deprecation of my `PosixParser`. This is an absolute mess.

Due to us having to retain compatibility we have two "unknown" parameters. The first command for Apktool (`b`, `d`, `if`, `empty-framework` or `publicize-resources`) can not be parsed through `DefaultParser` as they are not leading with a `--` or `-`. 

This was easy enough to just manually iterate the `args` list, but the next error we hit is the dumb options of the `DefaultParser` which can either die out when it encounters an unknown property or skip parsing all attributes after the unknown one.

Since verbose/quiet mode aren't specific to any command. They go first like `apktool -v d framework-res.apk -f`. This doesn't work because our into commandLine parser is only looking for verbosity, and then the sub-command. Since `-f` is part of the decode command, it fails

```
➜ apktool -v d framework-res.apk -f
Unrecognized option: -f
```

So if we think we are creativity and disable that check. The `DefaultParser` hits the `d` or `b` as the sub-command, doesn't recognize and drops all commands after that. Like the options and you know the apk.

So the obvious solution is to throw ALL commands into the same option bundle, so they aren't unknown during the processing of the verbosity, version & sub-command check and hack around the parser with some good ole argument iteration. This is what I already have had for years. I probably don't remember hitting the mess that is command line configurations. 

According to Stack - https://softwarerecs.stackexchange.com/questions/16450/what-library-should-i-use-for-handling-cli-arguments-for-my-java-program

Perhaps I should look into another. Apache Commons CLI is not good and with them deprecating the only parser I used and highly limiting the `DefaultParser` there is no future for Apktool in that. I've heard good reviews from Args4J and JCommander. Need to do some research and see what works. I'm tired of looking at deprecated functions.

**Comment by iBotPeaches** [comment]
Back to this. I spent a few days with JCommander as thats what the smali/baksmali project used. While setup was easy and creating commands worked out, I absolutely hated the default usage() output. 

Short of overriding a ton of methods, this is not possible to change currently. This is such a poor reason to not pick a CLI tool, but its a real personal preference for me to have the usage/cli output be in a format I like.

The entire reason of rewriting to the now defunct PosixParser was to have a condensed output allowing the separation of advanced/normal options. So putting this back on the back burner until I check out Args4J.

**Comment by Lanchon** [comment]
hey,

yeah, as i read the messages now i was about to propose JCommander due to JF using it for smali.

> This is such a poor reason to not pick a CLI tool

lolol yes! but then it's your project so you have to like it :)

thanks!
